### ISSUE TITLE
我刚更新了，但报错了，TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by jianyiblog** [mythsman/hexo-douban#105]
<img width="500" alt="WeChata83395fd105ef2545e7079a15641d264" src="https://user-images.githubusercontent.com/42142325/200484475-79c10882-1173-4eed-b14c-de783fb84a36.png">

**Comment by mythsman** [comment]
你的 hexo 版本是？

**Comment by jianyiblog** [comment]
> 你的 hexo 版本是？

4.3.0

**Comment by mythsman** [comment]
hexo 可以升下 6.x 试试么？

**Comment by mythsman** [comment]
我知道了，你说的是 hexo-cli 的版本。

问题复现了，是 hexo-log 依赖版本的问题，已在 2.0.3 修复；同时修复了 高版本 node  下失败的问题，可以再试下。

**Comment by jianyiblog** [comment]
> 我知道了，你说的是 hexo-cli 的版本。
> 
> 问题复现了，是 hexo-log 依赖版本的问题，已在 2.0.4 修复；同时修复了 高版本 node 下失败的问题，可以再试下。

好，辛苦了，我试试

**Comment by jianyiblog** [comment]
> 我知道了，你说的是 hexo-cli 的版本。
> 
> 问题复现了，是 hexo-log 依赖版本的问题，已在 2.0.4 修复；同时修复了 高版本 node 下失败的问题，可以再试下。
大佬，我试了已经，但一直提示当前账号录入中。还是拉不到数据。我从昨晚凌晨开始拉取的，到现在也没有数据

**Comment by jianyiblog** [comment]
> 我知道了，你说的是 hexo-cli 的版本。
> 
> 问题复现了，是 hexo-log 依赖版本的问题，已在 2.0.4 修复；同时修复了 高版本 node 下失败的问题，可以再试下。

大佬，我试了已经，但一直提示当前账号录入中。还是拉不到数据。我从昨晚凌晨开始拉取的，到现在也没有数据

**Comment by mythsman** [comment]
🤔感觉是夜里更新数据有坑，我刚才后台重试了下又都没问题了，你可以再试试。

今天晚上12点左右我再测测看。。。

**Comment by jianyiblog** [comment]
> 🤔感觉是夜里更新数据有坑，我刚才后台重试了下又都没问题了，你可以再试试。
> 
> 今天晚上12点左右我再测测看。。。

大佬，我可以拉到了，但是存在封面一直加载的情况。
<img width="481" alt="WeChat85d03e38f81d4d2f1a23fde82120d484" src="https://user-images.githubusercontent.com/42142325/200738425-82f72d67-2e3e-40fb-972a-928874678f7a.png">
<img width="859" alt="WeChata37c7112628121bd5881ff8a90463690" src="https://user-images.githubusercontent.com/42142325/200738434-e780482b-9f08-47ae-8cfe-6f35329897ce.png">

**Comment by mythsman** [comment]
应该是主题的问题，试试在header里加 <meta name="referrer" content="no-referrer" />  看看

**Comment by jianyiblog** [comment]
> 应该是主题的问题，试试在header里加 `<meta name="referrer" content="no-referrer" />` 看看

这个标签是加在哪个文件里，我是小白（捂脸笑

**Comment by mythsman** [comment]
看了下你的，似乎不是这个问题，我再看看。

**Comment by mythsman** [comment]
看了下应该是你的主题加了一个响应式的配置，导致了 srcset 设置的不对。我这边兼容下，试下 2.0.6

**Comment by jianyiblog** [comment]
> 看了下应该是你的主题加了一个响应式的配置，导致了 srcset 设置的不对。我这边兼容下，试下 2.0.6

 好，麻烦啦

**Comment by jianyiblog** [comment]
> 看了下应该是你的主题加了一个响应式的配置，导致了 srcset 设置的不对。我这边兼容下，试下 2.0.6

升级到2.0.6后，重新拉取后，依旧一直在加载封面😭

**Comment by mythsman** [comment]
你deploy一下我看看

**Comment by jianyiblog** [comment]
> 你deploy一下我看看
<img width="806" alt="WeChat497bbf420a20d25a4ac7d27f955906f1" src="https://user-images.githubusercontent.com/42142325/200744764-543b655a-ae9c-42e9-8a81-261d7803447f.png">

**Comment by jianyiblog** [comment]
> 你deploy一下我看看

还一个问题是电影的数据没有区分在看想看和已看，全部罗列在了一页里

**Comment by mythsman** [comment]
> 

感觉这个主题有坑，这个问题你刷新下页面就好了。。。。

**Comment by jianyiblog** [comment]
> > 还一个问题是电影的数据没有区分在看想看和已看，全部罗列在了一页里
> 
> 感觉这个主题有坑，这个问题你刷新下页面就好了。。。。

我在怀疑是不是我的主题设置有问题，就是我的页面与页面之间的跳转，不是重新加载刷新，而好像是本地切换不需要刷新。我现在还不知道怎么改这个方式

**Comment by mythsman** [comment]
> 我在怀疑是不是我的主题设置有问题，就是我的页面与页面之间的跳转，不是重新加载刷新，而好像是本地切换不需要刷新。我现在还不知道怎么改这个方式

哦，你这个主题走的前端路由。。。难怪我的js没生效。。。我看看咋兼容吧。。。

**Comment by mythsman** [comment]
尝试修一下，但是我这边不太好复现，你再试试 2.0.7 吧
