### ISSUE TITLE
ID失效？

### ISSUE THREAD

**Issue by sheldon123z** [mythsman/hexo-douban#107]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本。

如疑似遇到 bug ，请提供当前的 hexo 版本、以及当前使用的浏览器等信息。

doubanID 接口似乎是不管用了，所以会一直产生用户ID输入错误的提示？
<img width="563" alt="image" src="https://user-images.githubusercontent.com/42455304/201604581-a5972bec-9b0b-4019-b688-74ae9c7a1e1b.png">

**Comment by hyh981006** [comment]
要的是数字ID，不是豆瓣的id了哦，我也遇到过，改成数字id就好了

**Comment by mythsman** [comment]
是纯数字哦。。。不是 u-xxxx

**Comment by mythsman** [comment]
也不带大括号，我更新下文档吧。。。

**Comment by sheldon123z** [comment]
我发现问题了，之前的yaml文件里填写id的地方是`user`,现在改成了`id`
