### ISSUE TITLE
为什么湖出现这个情况呢，打开是这个样子，刷新一下才能好，作者有时间麻烦帮忙看一下呗

### ISSUE THREAD

**Issue by hyh981006** [mythsman/hexo-douban#108]
我根据您的配置后在浏览器打开后，第一次会出现以下这个效果，刷新一下一般情况下就好了,如果作者有时间麻烦帮忙看一下，感激不尽
点击这个是截图【电影，游戏，书籍都会出现】

> ](https://blog.gmcj0816.top/img/Snipaste_2022-11-14_16-01-48.jpg)
我的博客地址：https://blog.gmcj0816.top/

**Comment by mythsman** [comment]
你用的主题是 hexo-theme-butterfly 么？有做什么配置么？我直接在这个主题下测试是没问题的。。。

**Comment by mythsman** [comment]
像是对前端路由的兼容性不好，不过我这边也没复现。。。

**Comment by mythsman** [comment]
咦？我看你已经修好了，是做了什么么？

**Comment by hyh981006** [comment]
我也在想这个问题，但是确实没找到在哪里

**Comment by hyh981006** [comment]
这个问题在第一次进入之后出现，当刷新一下就会好

**Comment by mythsman** [comment]
> 这个问题在第一次进入之后出现，当刷新一下就会好

原因就是你们这些主题都是前端路由，进入新页面的时候，js没有执行到。。。

主要我这边没发复现，不太好解决。。。

**Comment by mythsman** [comment]
2.0.8 版本把图片懒加载的逻辑从 js 改成了用 img native 的 loading="lazy" ，可以再试下，起码图片应该能出来了。。。

**Comment by hyh981006** [comment]
图片加载确实没问题，但是其他的还是那样，我在想如何保证js执行到，刷新一次就能好使

**Comment by hyh981006** [comment]
这个问题我想到解决方案了，butterfly是有pjax的，这个大部分人会开启，这个需要进行以下的操作，一般即可修复
pjax:
  enable: true
  exclude:
    - /movies/
    - /games/
    - /books/

**Comment by mythsman** [comment]
👍 我也先加下说明，有时间看下可不可以直接兼容。
