### ISSUE TITLE
书和电影都有了，三件套是不是只差音乐了

### ISSUE THREAD

**Issue by itgoyo** [mythsman/hexo-douban#11]
书和电影都有了，三件套是不是只还差音乐了。
up，这个音乐专辑功能感觉可以有。

**Comment by mythsman** [comment]
搞个同步网易云的？

**Comment by itgoyo** [comment]
@mythsman 呀，网易云提供这种接口么，我之前想到了知识豆瓣的音乐，因为三个同样是豆瓣，网易云能搞到最好了不是么😄
