### ISSUE TITLE
Unhandled rejection TypeError: id.replaceAll is not a function

### ISSUE THREAD

**Issue by liugezhou** [mythsman/hexo-douban#110]
- node版本14
- hexo-douban: "^2.0.9"

在执行 hexo douban 命令的时候，昨天跟今天都多次出现这样的报错，没有找到原因，是只有我有这个问题吗🤣
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/29797703/202652417-5afdf21d-75ce-4ff9-bece-748196a5907d.png">

**Comment by mythsman** [comment]
估计是node版本兼容的问题，我确认下。

**Comment by mythsman** [comment]
![image](https://user-images.githubusercontent.com/11818556/202661802-17336bc5-d90e-49a5-af1c-97bb50451526.png)

**Comment by mythsman** [comment]
2.1.0 兼容了，试下。

**Comment by liugezhou** [comment]
> 2.1.0 兼容了，试下。

可以了可以了  🙏🙏
