### ISSUE TITLE
第二次同步数据不了

### ISSUE THREAD

**Issue by fyupeng** [mythsman/hexo-douban#112]
豆瓣版本2.1.0，浏览器用的是谷歌107.0.5304.122版本，就是首次可以录入，第二次更新一直没有生效，第二天再次更新也是一样。

**Comment by fyupeng** [comment]
请问作者是怎么更新的呀？我试了那个更新接口没有效果，这是我id号： 贰伍仈肆仈伍陆贰壹

**Comment by mythsman** [comment]
现在的策略是 24 小时最多更新一次 。

看你是昨天晚上八点半左右加的，还没到时间🤪

**Comment by fyupeng** [comment]
原来是这样呀，好的谢谢啦

**Comment by mythsman** [comment]
想了下似乎也没必要卡的这么死，现在把限制改到了 1小时，可以再瞅瞅。

**Comment by fyupeng** [comment]
一小时不知道会不会增大你服务器的压力？不过像maven开源仓库那种同步就做的很不错，虽然不会立即同步，但它们好像有一种策略，最长也能保证4小时内同步。

**Comment by mythsman** [comment]
没事，我这个是主动同步，不请求就不会同步🤥，压力可控。

**Comment by fyupeng** [comment]
好的。支持作者



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月1日(星期四) 中午1:39
收件人: ***@***.***&gt;; 
抄送: "fdk ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mythsman/hexo-douban] 第二次同步数据不了 (Issue #112)





 
没事，我这个是主动同步，不请求就不会同步🤥，压力可控。
