### ISSUE TITLE
pjax 的解决方法

### ISSUE THREAD

**Issue by jerryc127** [mythsman/hexo-douban#114]
现在很多主题都使用 pjax, 例如使用 https://github.com/MoOx/pjax

在 pjax 作用下，拉取页面时后，并不会触发 DOMContentLoaded，以至于这个插件的 initIndex() 和 initPagination() 并不会被调用

以下是解决方法

1.  最直接的方法，移除 DOMContentLoaded 后调用 initIndex 和 initPagination，改为直接调用
2. 使用回调,只针对 https://github.com/MoOx/pjax
```
document.addEventListener('pjax:complete', initIndex)
document.addEventListener('pjax:complete', initPagination)
```
4. 判断是否有 pjax,只针对 https://github.com/MoOx/pjax
判断 typeof new Pjax === 'object' ，是的话 直接调用参数，不是的话 等 DOMContentLoaded 后调用 initIndex 和 initPagination

5. 使用插件推荐的方法，有些主题提供页面排除于pjax外

所以 我建议 使用 1

**Comment by mythsman** [comment]
可以顺便帮忙提供一个 PR 么🤪

**Comment by jerryc127** [comment]
可以 只是你想采用哪一个方法

**Comment by mythsman** [comment]
我这边没有 pjax 的场景不太好测，先按照方案一看看吧

**Comment by mythsman** [comment]
已升版本 2.1.3
