### ISSUE TITLE
是取消了builtin吗？

### ISSUE THREAD

**Issue by chenwingsing** [mythsman/hexo-douban#118]
之前旧版本有这个觉得还挺不错，hexo g的时候可以顺便一起生成豆瓣信息，现在是要分开命令了吗 ，只能hexo douban -b来生成吗？

**Comment by mythsman** [comment]
本来是为了防止支持 builtin 之后数据一直更新导致后端数据来不及拉。不过现在加了一些去重逻辑，理论上只要用户没有新标记是不会触发用户维度的全量更新的。所以过段时间可以考虑把这个功能加回来。

**Comment by mythsman** [comment]
@chenwingsing  最新 v2.1.4 版本重新支持了 builtin 开关，可以重新尝试下。

**Comment by chenwingsing** [comment]
不错 谢谢
