### ISSUE TITLE
No douban id specified

### ISSUE THREAD

**Issue by HiderX** [mythsman/hexo-douban#119]
![image](https://user-images.githubusercontent.com/60884197/213346982-0e5d159f-394a-4880-afaf-a494edc9ace0.png)
这是错误信息
![image](https://user-images.githubusercontent.com/60884197/213347015-6e6cee6a-bdc5-4447-b931-a986b174e21b.png)
这是配置文件

**Comment by mythsman** [comment]
看下文档，配置里不是 user 是 id 。

**Comment by HiderX** [comment]
谢谢谢谢，我没注意到配置改了。
