### ISSUE TITLE
关于aath主题不能正常显示

### ISSUE THREAD

**Issue by KevinXiaoruZhu** [mythsman/hexo-douban#12]
**我这边试着用next和landscape主题使用该插件都是没问题的，但是换到aath主题就不能正常显示，想请教一下是什么原因，谢谢！**

具体表现为使用aath主题时访问movies为空白页，且有如下警告：
<img width="596" alt="screen shot 2018-02-05 at 2 01 51 pm" src="https://user-images.githubusercontent.com/16732926/35790626-5aef88d8-0a7e-11e8-8f08-e4064df301bd.png">

**Comment by mythsman** [comment]
原因是aath这个主题不太规范，我这边默认用的layout是page，而aath没有适配page的layout，所以会找不到。
当前我做了下处理，如果没有page的layout那就用post的layout，在0.2.5版本里就可以支持了，更新下插件就行:
```bash
$ npm upgrade hexo-douban
```
