### ISSUE TITLE
同样的配置Movies页面正常，books不管用？

### ISSUE THREAD

**Issue by HiderX** [mythsman/hexo-douban#121]
![image](https://user-images.githubusercontent.com/60884197/213357278-09f8ea9e-5424-444a-a6a8-3f2fc3224b94.png)
![image](https://user-images.githubusercontent.com/60884197/213357387-1926aeba-93f5-429b-81c1-4c77192c1f0e.png)

**Comment by mythsman** [comment]
额。。。books参数穿错了，我修下。。。

**Comment by mythsman** [comment]
可以升级下 2.1.5 版本。

**Comment by HiderX** [comment]
ok

**Comment by HiderX** [comment]
已经没问题了吗，谢谢回复
