### ISSUE TITLE
每个页面只显示10个，如何调整数量

### ISSUE THREAD

**Issue by hyh981006** [mythsman/hexo-douban#122]
每个页面只显示10个，请问如何调整数量
![image](https://user-images.githubusercontent.com/57065525/216041663-71f5f2d5-20b3-4231-9251-7221021e3f2f.png)

**Comment by mythsman** [comment]
明天我抽时间支持下配置。

**Comment by mythsman** [comment]
看起来比较简单，顺手改掉了，可以试下 2.1.6 版本，添加 item_per_page 参数。

具体可以看下更新后的配置文档。

**Comment by hyh981006** [comment]
非常Nice
