### ISSUE TITLE
生成页面失败

### ISSUE THREAD

**Issue by gao8319** [mythsman/hexo-douban#123]
hexo版本：6.3.0 插件版本：2.1.6 浏览器：谷歌  主题是next

![image](https://user-images.githubusercontent.com/60917570/216768092-1ebe705c-246f-4452-bb06-3c378c0073f0.png)

![image](https://user-images.githubusercontent.com/60917570/216768133-6cb11c69-5159-4636-b98b-367ed826b899.png)

之后等待一段时间hexo g ,hexo s  ,网站中没有生成页面

![image](https://user-images.githubusercontent.com/60917570/216768163-79e4467f-1753-4e57-85b3-fc45f4b8bba7.png)

求问作者可能是什么原因造成的呢？

**Comment by mythsman** [comment]
不要加 `-h` 你这个相当于是输出了帮助文档，没有发起请求。。。

**Comment by mythsman** [comment]
不要加 `-h` 你这个相当于是输出了帮助文档，没有发起请求。。。
