### ISSUE TITLE
无法load hexo-douban，页面展示为404（但是本地测试又是可以的）。请问是版本之间冲突的原因吗

### ISSUE THREAD

**Issue by liu-cui** [mythsman/hexo-douban#129]
![image](https://user-images.githubusercontent.com/55623869/235893748-39f99d93-7f3a-487e-bf3b-5157e427b5c8.png)

![image](https://user-images.githubusercontent.com/55623869/235894044-84dfc947-c834-442c-969b-e4955153ef46.png)

**Comment by mythsman** [comment]
没遇到过，单独敲 `hexo douban` 是啥输出呢？
