### ISSUE TITLE
豆瓣书单数据读取问题

### ISSUE THREAD

**Issue by stephen0316** [mythsman/hexo-douban#130]
一开始已读（154），删除一些书后，已读（131），但插件读取过来仍显示已读（150），仍存留已删除的书籍信息
<img width="443" alt="image" src="https://user-images.githubusercontent.com/55699331/236179098-c548c3ee-4036-4c95-b7ed-1644f9c19389.png">
<img width="474" alt="image" src="https://user-images.githubusercontent.com/55699331/236179140-b75d2f37-89e5-4ed6-b241-6ed02f99a99f.png">

**Comment by AuntYang** [comment]
数据不是实时更新的

**Comment by mythsman** [comment]
@stephen0316 哦，为了效率，现在默认只根据最近变更时间做增量更新，老的已经爬下来的评论条目是不会去处理的。。。

提供下你的 douban_id ，我等会加个接口，支持手动强刷下就行。

**Comment by stephen0316** [comment]
181263519；感谢🙏

**Comment by mythsman** [comment]
更新好了，可以再试试。

强制更新可以参考[这里](https://github.com/mythsman/mouban#%E5%BC%BA%E5%88%B6%E6%9B%B4%E6%96%B0%E7%94%A8%E6%88%B7)。

**Comment by stephen0316** [comment]
成功了！非常感谢
