### ISSUE TITLE
豆瓣好像设置图片资源防盗链了

### ISSUE THREAD

**Issue by W4J1e** [mythsman/hexo-douban#135]
比如直接访问：
https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2893270877.jpg 
会403

**Comment by mythsman** [comment]
应该是刚上的逻辑，有点恶心。。。

**Comment by sucooer** [comment]
我说怎么封面都没了

**Comment by xiayi0409** [comment]
hexo douban后显示WARN 当前用户录入中 导进去都是0是为什么啊（哭--

**Comment by mythsman** [comment]
> hexo douban后显示WARN 当前用户录入中 导进去都是0是为什么啊（哭--

明天再来看看，我先处理下防盗链的事情，处理好应该就会恢复。

**Comment by mythsman** [comment]
增量数据已经都做了转储，新增的图片应该都没问题了，存量数据后续慢慢刷吧。
