### ISSUE TITLE
数据拉取不全

### ISSUE THREAD

**Issue by MisteryLiuCode** [mythsman/hexo-douban#137]
### 环境
hexo: 6.3.0
hexo-cli: 4.3.1
os: linux 3.10.0-1160.71.1.el7.x86_64 CentOS Linux 7 (Core)
node: 14.21.1
v8: 8.4.371.23-node.87
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.6
openssl: 1.1.1q
cldr: 40.0
icu: 70.1
tz: 2022e
unicode: 14.0
### 问题
数据拉取不完整。

执行操作：

hexo clean
hexo douban
### 输出：
INFO  3 (wish), 1 (do),15 (collect) book loaded in 1364 ms
INFO  0 (wish), 1 (do),15 (collect) movie loaded in 1473 ms
通过接口https://mouban.mythsman.com/guest/user_movie获取到的信息如下：

"user": {
	"id": 251106444,
	"domain": "l19980923",
	"name": "l198923.",
	"thumbnail": "https://img2.doubanio.com/icon/u251106444-1.jpg",
	"book_wish": 3,
	"book_do": 1,
	"book_collect": 26,
	"game_wish": 0,
	"game_do": 0,
	"game_collect": 0,
	"movie_wish": 0,
	"movie_do": 1,
	"movie_collect": 81,
	"song_wish": 0,
	"song_do": 0,
	"song_collect": 0,
	"publish_at": 1662373814,
	"sync_at": 1688970066,
	"check_at": 1689498400
}
"movie_collect":81一共只能拉取15个，这有办法解决吗？

**Comment by mythsman** [comment]
明天再来看下，这两天维护😏

**Comment by MisteryLiuCode** [comment]
今天看了一下，还是一样的结果，应该不是维护的问题，我上周也是这样

**Comment by mythsman** [comment]
触发了一个bug，已经修复。

**Comment by MisteryLiuCode** [comment]
可以了，感谢
