### ISSUE TITLE
豆瓣插件在发布时遇电影界面GET不到服务器

### ISSUE THREAD

**Issue by lb948174033** [mythsman/hexo-douban#14]
输入hexo g、hexo d、hexo、hexo s --debug时，均出现报错：
`Error: connect ECONNREFUSED 127.0.0.1:80 (req "error"), GET http:///people/173149290/collect?start=15&sort=time&rating=all&filter=all&mode=grid -1 (connected: false, keepalive socket: false)`
movies-generator.js里面将
`var watchedUrl = 'https://movie.douban.com/people/' + config.douban.user + '/collect';`注释，或者https换http，hexo可以发布，只是get不到豆瓣信息。

**Comment by mythsman** [comment]
发现豆瓣对前端代码做了一些修改，url都用了相对路径，因此报错。现在在0.2.9版本修复了这个bug。

**Comment by lb948174033** [comment]
非常感谢及时对插件做的修复及更新，辛苦了。
