### ISSUE TITLE
数据展示不全

### ISSUE THREAD

**Issue by MisteryLiuCode** [mythsman/hexo-douban#141]
环境
hexo：6.3.0
hexo-cli：4.3.1
操作系统：linux 3.10.0-1160.71.1.el7.x86_64 CentOS Linux 7（核心）
节点：14.21.1
v8：8.4.371.23-node.87
uv：1.42。 0
zlib：1.2.11
brotli：1.0.9
ares：1.18.1
模块：83
nghttp2：1.42.0
napi：8
llhttp：2.1.6
openssl：1.1.1q
cldr：40.0
icu：70.1
tz：2022e
unicode：14.0

问题
数据拉取不完整，书籍页面部分书籍不展示我的评论

执行操作：

Hexo Clean
Hexo 豆瓣

输出：部分书籍不展示评论
<img src="https://misteryliu.oss-cn-beijing.aliyuncs.com/imageimage-20230804114821600.png" alt="image-20230804114821600" style="zoom:33%;" />

<img src="https://misteryliu.oss-cn-beijing.aliyuncs.com/imageimage-20230804114900505.png" alt="image-20230804114900505" style="zoom:33%;" />

**Comment by mythsman** [comment]
douban id 发下

**Comment by MisteryLiuCode** [comment]
您好
douban:
  id: 251106444

**Comment by mythsman** [comment]
看起来是评论更新过吧？一开始没有评论，后来有了？
如果是的话，我这里是不会更新的。想要更新的话，可以再新评论一个别的，这样就会触发新一轮的更新。

**Comment by MisteryLiuCode** [comment]
你是说再评论一个别的书吗

**Comment by mythsman** [comment]
> 你是说再评论一个别的书吗

嗯。

**Comment by MisteryLiuCode** [comment]
忘记试了，现在可以了。
