### ISSUE TITLE
页面刷新才显示问题

### ISSUE THREAD

**Issue by RediYo** [mythsman/hexo-douban#143]
hexo 版本:
6.3.0
hexo-douban 版本:
^2.2.2
douban id :
219077906
问题描述:
<img width="546" alt="image" src="https://github.com/mythsman/hexo-douban/assets/50956975/eac65eef-70bd-4688-a2c5-36aea6f68039">
我刷新页面才会显示全部的item，否则就是如图片所示。我开启了pjax。

**Comment by mythsman** [comment]
pjax 已经四五年不维护了，坑比较多，这里不再兼容。
