### ISSUE TITLE
使用命令升级之后，每次hexo s命令都提示Plugin load failed: hexo-douban

### ISSUE THREAD

**Issue by hormoyo** [mythsman/hexo-douban#144]
hexo 版本:6.3.0

hexo-douban 版本:2.2.2

douban id :1563307

问题描述:
之前hexo-douban版本2.1.7时，页面上总是显示我的书和电影都是0，然后看新的版本原来config里user改成id了，于是按教程改了。
接着使用npm install hexo-douban --save重新安装
提示found 52 vulnerabilities (6 low, 17 moderate, 19 high, 10 critical)
  run `npm audit fix` to fix them
去fix了一下。
但之后再次hexo g 或者hexo s 的时候，就一直提示“Plugin load failed: hexo-douban”

何解呀？

**Comment by mythsman** [comment]
node版本有点低了，往上升升看。。。 https://github.com/mythsman/hexo-douban/issues/142

**Comment by hormoyo** [comment]
> node版本有点低了，往上升升看。。。 #142

哦~~我试试

**Comment by hormoyo** [comment]
> node版本有点低了，往上升升看。。。 #142

hexo: 6.3.0
hexo-cli: 4.3.0
os: darwin 22.5.0 13.4.1

node: 20.5.1
acorn: 8.10.0
ada: 2.5.1
ares: 1.19.1
base64: 0.5.0
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.1
icu: 73.2
llhttp: 8.1.1
modules: 115
napi: 9
nghttp2: 1.55.1
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.10+quic
simdutf: 3.2.14
tz: 2023c
undici: 5.22.1
unicode: 15.0
uv: 1.46.0
uvwasi: 0.0.18
v8: 11.3.244.8-node.10
zlib: 1.2.13.1-motley

已经升级了……救命啊，安装上了，但之后每次我hexo 命令就提示：Deprecated config detected: "external_link" with a Boolean value is deprecated. 

然后hexo s 的页面是乱码了😭

**Comment by mythsman** [comment]
步子太大扯着蛋了，其他插件不兼容了的样子。。。
node降到16或者19看看。

**Comment by hormoyo** [comment]
> 步子太大扯着蛋了，其他插件不兼容了的样子。。。 node降到16或者19看看。

降到16.5.0了……还是不行 ，hexo s过程是：
INFO  Validating config
INFO  Start processing
WARN  当前用户录入中
INFO  0 (wish), 0 (do),0 (collect) movie loaded in 591 ms
WARN  当前用户录入中
INFO  0 (wish), 0 (do),0 (collect) book loaded in 612 ms

然后页面还是崩的😭

**Comment by mythsman** [comment]
录入中了，等个把小时就好了。

**Comment by hormoyo** [comment]
> 录入中了，等个把小时就好了。

现在hexo s 页面是乱码也是这个原因吗？

**Comment by mythsman** [comment]
这就不清楚了，可以自己排查下。。。
