### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ql-isaac** [mythsman/hexo-douban#145]
hexo 版本:v5.4.2

hexo-douban 版本:v2.2.2

douban id :214534818

问题描述:大佬你的服务是不是报502了
![154CC1F1](https://github.com/mythsman/hexo-douban/assets/53886119/f4200056-7124-41db-9dd8-38f7e5c1c0a0)

**Comment by mythsman** [comment]
刚迁服务器就被发现了。。。
在做停机迁移。。。大概明天才能好。。。
