### ISSUE TITLE
mouban现在闭源了吗？

### ISSUE THREAD

**Issue by AlliotTech** [mythsman/hexo-douban#146]
Hi ， 最近从老版本升上来的， 才发现新版本有了服务端，不过readme中的mouban看起来是闭源了吗？

**Comment by AlliotTech** [comment]
BTW， mouban的后端现在502了。

**Comment by mythsman** [comment]
权宜之计。

PS，服务部在家里，今天家里断网了，得晚上回家看看。。

**Comment by mythsman** [comment]
mouban 重新开开了，有兴趣可以看。

服务也已经恢复了，最近光猫有点问题，只能再观察观察。
