### ISSUE TITLE
与hexo-optimize冲突

### ISSUE THREAD

**Issue by AlliotTech** [mythsman/hexo-douban#147]
hexo: 6.3.0
hexo-cli: 4.3.1
os: darwin 21.6.0 12.6.8

node: 18.17.1
acorn: 8.8.2
ada: 2.5.0
ares: 1.19.1
brotli: 1.0.9
cldr: 43.0
icu: 73.1
llhttp: 6.0.11
modules: 108
napi: 9
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.10+quic
simdutf: 3.2.12
tz: 2023c
undici: 5.22.1
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.18
v8: 10.2.154.26-node.26
zlib: 1.2.13.1-motley

问题描述:
当启用filter_optimize时，会出现如下错误：  
``` 
Unhandled rejection TypeError: self.route.get(...)._data is not a function
```

疑似优先级问题（未证实）
临时解决方法： 
启用 `builtin: true`

**Comment by mythsman** [comment]
可以升级 [v2.2.3](https://github.com/mythsman/hexo-douban/releases/tag/v2.2.3) 看下。

**Comment by AlliotTech** [comment]
测试后已经解决， 神速
