### ISSUE TITLE
书评不显示问题

### ISSUE THREAD

**Issue by junfish** [mythsman/hexo-douban#148]
hexo: 5.4.2
hexo-cli: 3.1.0
os: Darwin 22.1.0 darwin arm64
node: 20.5.1
acorn: 8.10.0
ada: 2.5.1
ares: 1.19.1
base64: 0.5.0
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.1
icu: 73.2
llhttp: 8.1.1
modules: 115
napi: 9
nghttp2: 1.55.1
openssl: 3.1.2
simdutf: 3.2.14
tz: 2023c
undici: 5.22.1
unicode: 15.0
uv: 1.46.0
uvwasi: 0.0.18
v8: 11.3.244.8-node.10
zlib: 1.2.11

hexo-douban 版本: 2.2.2

douban id : 214963638

问题描述: 同问题 #141 

#141 解决方案已尝试，无效果。

**Comment by mythsman** [comment]
多谢反馈，你说的对。

页面有变化导致数据没爬到，现在已经修复了，可以再看下。
