### ISSUE TITLE
Connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by qinyuanpei** [mythsman/hexo-douban#15]
最近发现该插件在生成页面的时候会出现以下错误，昨天TravisCI同样执行失败了：
<img width="695" alt="_20180322092047" src="https://user-images.githubusercontent.com/7688258/37745897-6c81fd54-2db2-11e8-8a8a-7da4ecb577f7.png">
可以告诉我具体是因为什么原因吗？如果是我nodejs环境有问题，比如这个端口被占用，可持续集成服务的环境应该不会出现这种问题啊，我检查你代码里请求的URL，没有错误啊，为什么这里baseURL没有了呢？费解啊

**Comment by mythsman** [comment]
这个问题在之前的 ISSUE #14  里解决过了，原因是豆瓣网站的url做了调整，更新一下插件就行~
