### ISSUE TITLE
生成的页面没有评论区

### ISSUE THREAD

**Issue by naosense** [mythsman/hexo-douban#150]
node 版本:16.19.0
hexo 版本: 6.3.0

hexo-douban 版本: 2.2.3

douban id : 55551545

问题描述: 生成的页面没有评论区diqus，使用md生成的文档是有的

**Comment by mythsman** [comment]
看下你默认生成 disqus 的 layout 是什么，尝试在配置文件里配置下 customize_layout 。

**Comment by naosense** [comment]
customize_layout配置的page，page.ejs里include了评论区

**Comment by mythsman** [comment]
你用的什么主题，我这里无法复现你的问题。

**Comment by naosense** [comment]
应该是我的问题，我的页面有个判断
```
if (is_post() || is_page()) {
  // disqus
}
```
去掉这个判断就有了，不过话说books不是page吗，为啥这个逻辑过不了？

**Comment by mythsman** [comment]
看了下 hexo 的代码，他这里的 is_page() 和 is_post() 只识别 hexo 自己的 generator 生成的，并不是对 layout 层统一做的逻辑，参考 [page.js](https://github.com/hexojs/hexo/blob/b267475d306b616ab9a3cd37e904d36524aad8be/lib/plugins/generator/page.js#L17)。hexo-douban 自定义的 generator 并没有支持这个。

**Comment by naosense** [comment]
好的，多谢解答！
