### ISSUE TITLE
为什么每次执行 hexo generate 指令，都会删除插件生成好的 index.html 文件？

### ISSUE THREAD

**Issue by guaxichi** [mythsman/hexo-douban#152]
如题。因为本人刚接触博客搭建，而且完全零基础，所以这个问题可能有点傻，而且这应该也不属于插件本身的问题。只是想请教一下，出现这个情况是哪里出现了问题，该怎么解决？谢谢了。

**Comment by mythsman** [comment]
看了下是 hexo 的数据缓存的问题。我测试了下，以下步骤可以复现这个badcase：

1. hexo clean 
2. 设置 builtin: true
3. hexo g
4. 设置 buildin: false
5. hexo g

后续无论如何执行 hexo douban，再执行 hexo g 都会出现下面 的日志：

```
INFO  Start processing
INFO  Files loaded in 359 ms
INFO  Deleted: games/index.html
INFO  Deleted: books/index.html
INFO  Deleted: movies/index.html
INFO  Deleted: songs/index.html
```

原因就是 配置 builtin: true 后， db.json 会记录 douban 相关页面的信息；但是当重新 builtin: false 后，这个信息并没有消失。这样后续执行 hexo g 之后，hexo 找不到这些页面信息对应的渲染函数，就会执行自动清理逻辑。

解决问题只需要在修改 builtin 参数后执行一下 hexo clean，清理缓存文件即可。

**Comment by guaxichi** [comment]
问题解决啦，十分感谢！
