### ISSUE TITLE
强制刷新评论不更新

### ISSUE THREAD

**Issue by naosense** [mythsman/hexo-douban#153]
我更新了某本书的评论，调用了强制刷新接口，
<img width="559" alt="image" src="https://github.com/mythsman/hexo-douban/assets/2225426/397fe594-08f1-488d-a891-3f59c5575ef1">

但是我的页面评论并没有更新

**Comment by mythsman** [comment]
发起后需要等一会，我看你这个id 是在 18:40:03 更新的，可以再看下。

**Comment by naosense** [comment]
好了多谢
