### ISSUE TITLE
hexo douban不会触发generate books movies操作

### ISSUE THREAD

**Issue by AlliotTech** [mythsman/hexo-douban#157]
node 版本: v20.9.0

hexo 版本: 7.0.0

hexo-douban 版本: 2.2.4

douban id : 

问题描述:

dependencies:
- hexo-douban 2.2.3
+ hexo-douban 2.2.4

升级后引入了一个问题：   hexo douban不会触发generate books movies操作。
<img width="865" alt="image" src="https://github.com/mythsman/hexo-douban/assets/24980252/c2bce7c2-03d9-49fc-9516-d8df82519d4a">

**Comment by mythsman** [comment]
奇怪，我这里复现不了。。。你 hexo clean 一把再试试？

**Comment by AlliotTech** [comment]
诶。。我这边稳定复现，降到2.2.3就正常，我对比了一下两个版本的代码，看到俩版本只是更新了依赖与一个字段。  测试了一下，预计是某个依赖更新引入的问题。

**Comment by mythsman** [comment]
看代码diff是看不出问题的。。。因为我 npm 打的包版本跟 git 包版本没对上。。。2.2.5版本修了一把，可以再看看。

**Comment by AlliotTech** [comment]
问题依旧

**Comment by mythsman** [comment]
哦，复现了，我再查查。。。

**Comment by AlliotTech** [comment]
<img width="890" alt="image" src="https://github.com/mythsman/hexo-douban/assets/24980252/1f0be840-1cb9-4048-9f10-5fb18c56f163">
是的 依旧不行。
还有一个问题就是，使用hexo-blog-encrypt后，hexo douban也会触发hexo-blog-encrypt，这个应该是非必要的操作，带来了一定时间的开销。

**Comment by mythsman** [comment]
试下 2.2.6 。

**Comment by AlliotTech** [comment]
2.2.6似乎依旧修复了这个问题✅
