### ISSUE TITLE
影片信息错误

### ISSUE THREAD

**Issue by AlliotTech** [mythsman/hexo-douban#158]
问题描述:  似乎 “河边的错误” 影片的数据是错误的。
爬成了 “孩子”： 
https://movie.douban.com/subject/35256092/  
<img width="591" alt="image" src="https://github.com/mythsman/hexo-douban/assets/24980252/c5bd6367-45e4-4768-be07-c4127dc0356d">

**Comment by mythsman** [comment]
这种一般都是影片名字有改动了，我这里的数据更新频率比较低。。。

重新触发下强制更新，现在就一致了。

https://mouban.mythsman.com/admin/refresh_item?type=2&id=35256092
