### ISSUE TITLE
豆瓣主页书单展示不全

### ISSUE THREAD

**Issue by chechuan** [mythsman/hexo-douban#159]
node 版本: 21.0.0

hexo 版本: 6.3.0
hexo-douban 版本: 2.2.3

douban id : 250517910

问题描述: 豆瓣书单只显示了一部分已读的书，还有一半的书没有展示，hexo clean、hexo douban、hexo g、hexo deploy,这些都执行了，不知道是什么原因。

**Comment by chechuan** [comment]
正在将hexo-douban升级到最新版本，试图解决

**Comment by mythsman** [comment]
刚才后台强制更新了一把，应该已经有了。可能是触发了某个策略bug，回头再查查。

**Comment by chechuan** [comment]
> 刚才后台强制更新了一把，应该已经有了。可能是触发了某个策略bug，回头再查查。

哇塞，可以了，非常感谢。
