### ISSUE TITLE
关于hexo s的问题

### ISSUE THREAD

**Issue by AlliotTech** [mythsman/hexo-douban#16]
每次hexo s都会不停的对豆瓣接口进行请求，这就导致在断网或是网络环境不好的情况下运行hexo s会报错。

**Comment by mythsman** [comment]
是的，毕竟数据是得联网才能获得的，看来还是要加一下断网下的处理才行。

**Comment by AlliotTech** [comment]
~ 晚上好~ (刚才无意折腾博客，没看时间，打扰到 很抱歉~)建议可以添加一个开关
另外刚才发现读书页的预览图URL有问题，无法加载。  不知道是不是接口的原因。

**Comment by AlliotTech** [comment]
已正常。。。 貌似是开了防盗链还是怎么的。。。请求全403.。

**Comment by AlliotTech** [comment]
👏
