### ISSUE TITLE
hexo douban 显示“No douban config specified”

### ISSUE THREAD

**Issue by cath-gh** [mythsman/hexo-douban#161]
node 版本: v18.17.1

hexo 版本: 6.3.0

hexo-douban 版本: 2.2.6

douban id : 2896809

问题描述: hexo douban 显示“No douban config specified”

clean过了，hexo g之前之后都是这个显示，_config文件配置就是复制的模版，只改了douban id

**Comment by mythsman** [comment]
是不是你配置写的地方不对，这个基本就是没读到你的配置导致的。。。
