### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by stephen0316** [mythsman/hexo-douban#162]
node 版本:18.14.1

hexo 版本:7.0.0

hexo-douban 版本: 最新

douban id :181263519

问题描述:
首次进入书单/影单 页面无数据显示，每次需要手动刷新后才能正常显示
<img width="1727" alt="image" src="https://github.com/mythsman/hexo-douban/assets/55699331/f0b97818-430c-49c0-b1ff-3b9ae87111e3">
<img width="1727" alt="image" src="https://github.com/mythsman/hexo-douban/assets/55699331/f84d8fa8-0b18-4f34-95eb-5b14161c4c3c">

**Comment by mythsman** [comment]
是不是用了 pjax ，这个不兼容。

**Comment by stephen0316** [comment]
是的，只能这样了吗，有没有其他解决办法，大佬

**Comment by mythsman** [comment]
pjax 已经不维护了，兼容起来比较麻烦，需要一些复杂配置，这里不打算兼容。

**Comment by stephen0316** [comment]
> pjax 已经不维护了，兼容起来比较麻烦，需要一些复杂配置，这里不打算兼容。

好的，感谢大佬
