### ISSUE TITLE
豆瓣数据同步问题

### ISSUE THREAD

**Issue by chechuan** [mythsman/hexo-douban#163]
node 版本: v21.0.0

hexo 版本: 6.3.0

hexo-douban 版本: 2.2.6

douban id : 250517910

问题描述: 豆瓣读书模块的数据同步问题依然存在，尽管我已经尝试执行了所有相关命令

**Comment by mythsman** [comment]
如果问题指的是历史删除过的数据同步的话，可以看下这里：
https://github.com/mythsman/mouban?tab=readme-ov-file#%E5%BC%BA%E5%88%B6%E6%9B%B4%E6%96%B0%E7%94%A8%E6%88%B7

**Comment by chechuan** [comment]
> 如果问题指的是历史删除过的数据同步的话，可以看下面这里： [https://github.com/mythsman/mouban?tab=readme-ov-file#%E5%BC%BA%E5%88%B6 %E6%9B%B4%E6%96%B0%E7%94%A8%E6%88%B7](https://github.com/mythsman/mouban?tab=readme-ov-file#%E5%BC%BA%E5%88%B6%E6%9B%B4%E6%96%B0%E7%94%A8%E6%88%B7)

学习了

**Comment by AdamZhengLu** [comment]
Good Job!!!
