### ISSUE TITLE
读书插件在firefox中不加载图片

### ISSUE THREAD

**Issue by lieh666** [mythsman/hexo-douban#17]
关于反防盗链
![default](https://user-images.githubusercontent.com/23148158/38462368-c8f208d6-3b18-11e8-9569-95d5c694f329.png)
在firefox中没有成功，图片请求头还是带上了referrer
![default](https://user-images.githubusercontent.com/23148158/38462381-068bd3de-3b19-11e8-98e0-ad1f1538f0a1.png)
导致图片无法显示。
![default](https://user-images.githubusercontent.com/23148158/38462438-dacaeef0-3b19-11e8-9b14-c148a429ad3c.png)

**Comment by mythsman** [comment]
emmm，我研究下。。

**Comment by mythsman** [comment]
@lieh666 照着mdn搞了搞，0.2.14里修复了。。。

**Comment by lieh666** [comment]
嗯，我也看了下，好像是要把策略放到具体的标签里面。

**Comment by lieh666** [comment]
可是为什么<meta name=”referrer” content=”no-referrer” />这个属性不好使呢。这个你清楚么？

**Comment by mythsman** [comment]
大概是firefox不认吧，以mdn为准。。。。
