### ISSUE TITLE
功能建议| 在读 想读 已读 

### ISSUE THREAD

**Issue by lalalll-lalalll** [mythsman/hexo-douban#171]
希望可以添加配置设置允许随意自定义 "在读" "想读" "已读"  三者的顺序

**Comment by mythsman** [comment]
可以升级 2.3.0 版本，看一下README，改一下 actions 参数。

**Comment by lalalll-lalalll** [comment]
已经解决问题了!感谢!
但还有一点小建议,actions默认是聚焦第一个标签,不知道这点可以自定义么

**Comment by mythsman** [comment]
感觉没啥太大必要，搞太多复杂配置。调整下顺序到第一个就好了。

**Comment by lalalll-lalalll** [comment]
首先感谢开发者及时的回复和更新,本评论无任何负面倾向无任何负面倾向无任何负面倾向↓

还是回到v2.2.7版本自己修改了下`index.ejs`代码,实现了自己的目的
更新后的版本有两个问题是比较难受的:
1.并没有达到目的,而且架构完全看不懂了T.T
2.完全与pjax不兼容了,旧版本好歹可以给`hexo-douban-tabs`下的`script`添加`data-pjax`属性解决,新版本是整个页面都错误了,无从下手...

因为本人的博客同时装有[hexo-bilibili-bangumi](https://github.com/HCLonely/hexo-bilibili-bangumi),其可以选择第一个展示的项目,但是不能调整顺序,所以想和本插件实现一个风格统一,以下是最终效果:
https://lalalll-lalalll.github.io/books/
anime页面:https://lalalll-lalalll.github.io/anime/

最终还是感谢开发者的奉献和努力,提供了如此高质的插件,毕竟后者也是参考自本插件.

**Comment by mythsman** [comment]
理解，刚开始折腾的时候都是完美主义者，不过弄久了就知道这个世界就是那么不完美╮(╯▽╰)╭
另外 pjax 这个东西感觉是静态网页和spa之间的融合怪，个人还是不太喜欢。。。
