### ISSUE TITLE
生成成功，但是并未写入？

### ISSUE THREAD

**Issue by itangqiao** [mythsman/hexo-douban#172]
node 版本:
v20.10.0

hexo 版本:
    "hexo": "7.2.0",
    "hexo-theme-stellar": "^1.27.0"

hexo-douban 版本:
    "hexo-douban": "^2.2.7",

douban id :
162448367

问题描述:

![image](https://github.com/mythsman/hexo-douban/assets/44393379/e9a172f9-c511-43dc-9a9c-9a7bdcec5bf1)
![image](https://github.com/mythsman/hexo-douban/assets/44393379/1a2a16ad-ce9a-4da9-843d-ac639cf36e34)

控制台显示生成成功，但是并没有看见写入~

**Comment by mythsman** [comment]
生成在 public 文件夹下，是不是被你 gitignore 了

**Comment by itangqiao** [comment]
> 生成在 public 文件夹下，是不是被你 gitignore 了

是的，看见了😅
