### ISSUE TITLE
idouban-picture 图片显示溢出

### ISSUE THREAD

**Issue by brycezhang** [mythsman/hexo-douban#175]
node 版本: 22.0.0

hexo 版本: 7.2.0

hexo-douban 版本: 2.3.3

问题描述:
`idouban-picture img` 没有设置高度限制，会出现显示溢出的问题，我临时手动添加样式控制了一下，不过base64的样式还是需要改一下。
<img width="427" alt="iShot_2024-06-06_13 49 24" src="https://github.com/mythsman/hexo-douban/assets/3113838/336a36e4-f533-4955-8d48-9cb3358edee3">

```
.idouban-picture img {
    max-width: 100%;
}
```

`idouban-picture img` 应该设置一个最大高度，不能超过 `idouban-item`的 `min-height-2*padding`，也就是130px。

```
.idouban-item {
    clear: both;
    border-bottom: 1px solid #ddd;
    min-height: 150px;
    padding: 10px 0;
    position: relative;
}
```

**Comment by mythsman** [comment]
试下 v2.3.5

**Comment by brycezhang** [comment]
可以了
