### ISSUE TITLE
页面显示异常

### ISSUE THREAD

**Issue by stephen0316** [mythsman/hexo-douban#177]
node 版本:18.14.1

hexo 版本:7.0.0

hexo-douban 版本:最新版

douban id :181263519

问题描述:从首页进入书单页面，显示空白
<img width="1727" alt="image" src="https://github.com/mythsman/hexo-douban/assets/55699331/f7987d8d-601a-4729-bdec-6e1e62bc90a0">
手动刷新后，才能正常加载出来
用开发者工具看，没有报错

**Comment by mythsman** [comment]
看起来是你放弃 pjax 之后找了个 swup 来替代🥲。
把 redefine 主题里的 single_page 关了可以解决问题。
如何兼容的话我还要再研究研究。

**Comment by stephen0316** [comment]
> 看起来是你放弃 pjax 之后找了个 swup 来替代🥲。 把 redefine 主题里的 single_page 关了可以解决问题。 如何兼容的话我还要再研究研究。

之前也出现过类似问题[问题描述](https://github.com/EvanNotFound/hexo-theme-redefine/issues/325#issue-2055568491)，一个大佬写了个脚本：

<img width="792" alt="image" src="https://github.com/mythsman/hexo-douban/assets/55699331/6cfaeca3-206d-4945-904a-b50e66497267">


帮我解决了这个问题，直到今天更新douban插件后，再次出现了问题，估计是新版本跟脚本有冲突？

**Comment by mythsman** [comment]
升下 v2.3.6 ，看下文档，加一个 swup: true ，兼容一把。

**Comment by stephen0316** [comment]
> 升下 v2.3.6 ，看下文档，加一个 swup: true ，兼容一把。

解决了！大佬🐮！另外还有个小小的疑问，怎么手动强制更新历史数据呀，必须要用到docker吗
<img width="751" alt="image" src="https://github.com/mythsman/hexo-douban/assets/55699331/0277287b-d7f3-4a5f-9dbb-f6868f40c26a">

**Comment by mythsman** [comment]
> > 升下 v2.3.6 ，看下文档，加一个 swup: true ，兼容一把。
> 
> 解决了！大佬🐮！另外还有个小小的疑问，怎么手动强制更新历史数据呀，必须要用到docker吗 <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/55699331/342199570-0277287b-d7f3-4a5f-9dbb-f6868f40c26a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDc1MDksIm5iZiI6MTcxOTIwNzIwOSwicGF0aCI6Ii81NTY5OTMzMS8zNDIxOTk1NzAtMDI3NzI4N2ItZDdmMy00YTVmLTlkYmItZjY4NjhmNDBjMjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA1MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjAzM2RhMjUxNWI2Y2Y2OTk1MWQ2Yjk5NmI3OWVmZDdjOGYyYzY5N2UyZjEyNjc1MmE3NDNmOGQyYTBkYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LRAoHT9NQJmEBxUunIAvUnNJAlM7wqd11Ug4OyEEd-0">

不用，域名换成 mouban.mythsman.com ，调用一把就好

**Comment by stephen0316** [comment]
> > > 升下 v2.3.6 ，看下文档，加一个 swup: true ，兼容一把。
> > 
> > 
> > 解决了！大佬🐮！另外还有个小小的疑问，怎么手动强制更新历史数据呀，必须要用到docker吗 <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/55699331/342199570-0277287b-d7f3-4a5f-9dbb-f6868f40c26a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDc1MDksIm5iZiI6MTcxOTIwNzIwOSwicGF0aCI6Ii81NTY5OTMzMS8zNDIxOTk1NzAtMDI3NzI4N2ItZDdmMy00YTVmLTlkYmItZjY4NjhmNDBjMjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA1MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjAzM2RhMjUxNWI2Y2Y2OTk1MWQ2Yjk5NmI3OWVmZDdjOGYyYzY5N2UyZjEyNjc1MmE3NDNmOGQyYTBkYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LRAoHT9NQJmEBxUunIAvUnNJAlM7wqd11Ug4OyEEd-0">
> 
> 不用，域名换成 mouban.mythsman.com ，调用一把就好

提示条目未收录是什么原因呢
<img width="344" alt="image" src="https://github.com/mythsman/hexo-douban/assets/55699331/804c45ae-1976-48d5-85d9-7ee1a558d936">

**Comment by mythsman** [comment]
确认下参数

**Comment by stephen0316** [comment]
> 确认下参数

`http://localhost:8080/admin/refresh_item?type={item_type}&id={item_douban_id}
`
这个item_douban_id就是我的豆瓣id吧，根据这个规则得出如下：
https://mouban.mythsman.com/admin/refresh_item?type=1&id=181263519
是item_type 的参数有问题吗

**Comment by mythsman** [comment]
> > 确认下参数
> 
> `http://localhost:8080/admin/refresh_item?type={item_type}&id={item_douban_id} ` 这个item_douban_id就是我的豆瓣id吧，根据这个规则得出如下： https://mouban.mythsman.com/admin/refresh_item?type=1&id=181263519 是item_type 的参数有问题吗

你应该是要更新用户吧，用 refresh_user 。

**Comment by stephen0316** [comment]
> > > 确认下参数
> > 
> > 
> > `http://localhost:8080/admin/refresh_item?type={item_type}&id={item_douban_id} ` 这个item_douban_id就是我的豆瓣id吧，根据这个规则得出如下： https://mouban.mythsman.com/admin/refresh_item?type=1&id=181263519 是item_type 的参数有问题吗
> 
> 你应该是要更新用户吧，用 refresh_user 。

我是想更新书单信息，有一些历史删除的数据仍存在着

**Comment by mythsman** [comment]
> > > > 确认下参数
> > > 
> > > 
> > > `http://localhost:8080/admin/refresh_item?type={item_type}&id={item_douban_id} ` 这个item_douban_id就是我的豆瓣id吧，根据这个规则得出如下： https://mouban.mythsman.com/admin/refresh_item?type=1&id=181263519 是item_type 的参数有问题吗
> > 
> > 
> > 你应该是要更新用户吧，用 refresh_user 。
> 
> 我是想更新书单信息，有一些历史删除的数据仍存在着

就是我这里 refresh_user 的意思。
