### ISSUE TITLE
Fetch data error: [cause]: Error: certificate has expired

### ISSUE THREAD

**Issue by Cactusinhand** [mythsman/hexo-douban#179]
node 版本:
v20.14.0
hexo 版本:
5.4.2
hexo-douban 版本:
2.3.6
douban id :

问题描述:
`CERT_HAS_EXPIRED`:

![image](https://github.com/user-attachments/assets/7cedeada-e060-4245-b784-a17934d33baf)

**Comment by mythsman** [comment]
已fix。

**Comment by Cactusinhand** [comment]
> 已fix。

大佬能讲一下是哪里出问题的吗，我看代码库没有修改。

**Comment by mythsman** [comment]
> > 已fix。
> 
> 大佬能讲一下是哪里出问题的吗，我看代码库没有修改。

服务器上的https证书过期了，同步了一下。
