### ISSUE TITLE
移动端豆瓣读书图片显示问题

### ISSUE THREAD

**Issue by chocoluffy** [mythsman/hexo-douban#18]
在网页端显示没有问题，包括用chrome的视图适配到移动端尺寸也ok，比如下图

![image](https://user-images.githubusercontent.com/13173251/38567461-4654fe86-3cb4-11e8-9fa9-022c8c74f349.png)，

但是如果直接从手机上打开网址会发现图片显示不出来，点击会有fancybox的报错信息，比如下两图：

![img_1179](https://user-images.githubusercontent.com/13173251/38567412-27bd1602-3cb4-11e8-88b3-34c89bcae446.PNG)
![img_1180](https://user-images.githubusercontent.com/13173251/38567587-9af7b80c-3cb4-11e8-9ba7-41f4052dcb09.PNG)

也比较好奇这种情况我应该怎么测试，会不会和fancybox相关，我尝试disable掉这个插件在`_config.xml`里`fancybox:false`，这个时候整个豆瓣读书都section都不会显示，但travis ci里没有报错。

博客主题 next-mist，
node版本 7,
博客连接 www.chocoluffy.com/books/

谢谢分享，很棒的插件！

**Comment by mythsman** [comment]
你用的手机浏览器是啥勒？我手机上是可以看的到的啊~~
![screenshot_2018-04-10-23-56-58-967_mark via](https://user-images.githubusercontent.com/11818556/38568298-ea54c596-3d1a-11e8-88f6-e10690535b83.png)

**Comment by chocoluffy** [comment]
我试了chrome和safari都没有显示，因为我坐标在加拿大，我尝试VPN回到国内再打开也没有显示。然后我怀疑会不会和asset cache有关，可我用chrome开anonymous模式也不行。谢谢楼主的及时回复！

**Comment by mythsman** [comment]
试试看能不能直接访问douban官网上看。。。vpn到国内也看不了确实很奇怪。。。

**Comment by chocoluffy** [comment]
貌似也不行，有点奇怪了。这个应该只是个例，谢谢楼主及时答复！
