### ISSUE TITLE
数据更新问题

### ISSUE THREAD

**Issue by xiaoyangst** [mythsman/hexo-douban#182]
问题描述:

就是之前被记录的书，在豆瓣这边已经取消了，为什么这边再次更新的时候那些记录还在？

是不是每次都会去读缓存，然后并不会更新缓存？

**Comment by mythsman** [comment]
目前用户的评论信息更新下载好后，后续只会进行增量更新。
如要强制更新，需要手动调一下相关接口。

https://github.com/mythsman/mouban?tab=readme-ov-file#%E5%BC%BA%E5%88%B6%E6%9B%B4%E6%96%B0%E7%94%A8%E6%88%B7

**Comment by xiaoyangst** [comment]
> Quote reply
> Reference i

item_type 取: 1-book 2-movie 3-game 4-song

http://localhost:8080/admin/refresh_item?type={item_type}&id={item_douban_id}

你这个  item_douban_id 指哪个？ 豆瓣用户 id ？

而且你这个IP地址，是我这边 hexo s 的那个地址吗？

**Comment by xiaoyangst** [comment]
就是我得自己去下载，然后搭建这个环境，自己去更新，对吧？

**Comment by xiaoyangst** [comment]
已经知道怎么处理了

**Comment by xiaoyangst** [comment]
更新之后什么时候生效呢？

**Comment by mythsman** [comment]
分钟级更新，吃个饭应该就好了。

**Comment by xiaoyangst** [comment]
> 分钟级更新，吃个饭应该就好了。

实际上并没有，按照你给的方式返回 success，但是还是没有成功

**Comment by cloudshadow7** [comment]
同问，更新用户接口成功，查询用户评论接口返回`user`是正确数据，但`comment`是旧数据，插件生成页面也是旧数据。

**Comment by mythsman** [comment]
> 同问，更新用户接口成功，查询用户评论接口返回`user`是正确数据，但`comment`是旧数据，插件生成页面也是旧数据。

提供下 id 我看看。

**Comment by cloudshadow7** [comment]
@mythsman 
id: 71286874    旧数据观影 113 条数据，删除一部分后剩下 62 条数据。
![生成页面](https://github.com/user-attachments/assets/3f5f9dd7-da58-420a-9aaa-2d1d4f0c8fe6)

**Comment by mythsman** [comment]
> @mythsman id: 71286874 旧数据观影 113 条数据，删除一部分后剩下 62 条数据。 ![生成页面](https://private-user-images.githubusercontent.com/32220342/398414657-3f5f9dd7-da58-420a-9aaa-2d1d4f0c8fe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDcwMDYsIm5iZiI6MTczNTA0NjcwNiwicGF0aCI6Ii8zMjIyMDM0Mi8zOTg0MTQ2NTctM2Y1ZjlkZDctZGE1OC00MjBhLTlhYWEtMmQxZDRmMGM4ZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDEzMjUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNDlhZTRlOWQ2NzIzNzI2ZDdmZTU2ZmU0MDVkYjdkZTUzNmIyMmUyZDg3NDQxNDM2Y2QwNzBjZjQxMThkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-xalcind8cZJ2FkNm_E02_kHWED94Wfzre2fJr-HABo)

已经手动帮你触发了，接口是：
https://mouban.mythsman.com/admin/refresh_user?id=71286874

再拉下数据，已经是最新的了。

**Comment by mythsman** [comment]
> > Quote reply
> > Reference i
> 
> item_type 取: 1-book 2-movie 3-game 4-song
> 
> [http://localhost:8080/admin/refresh_item?type={item_type}&id={item_douban_id}](http://localhost:8080/admin/refresh_item?type=%7Bitem_type%7D&id=%7Bitem_douban_id%7D)
> 
> 你这个 item_douban_id 指哪个？ 豆瓣用户 id ？
> 
> 而且你这个IP地址，是我这边 hexo s 的那个地址吗？

不是这个接口，是 refresh_user 的。

**Comment by xiaoyangst** [comment]
https://mouban.mythsman.com/admin/refresh_user?id=234844986

记录一下，下次直接复制
