### ISSUE TITLE
希望电影页面能不要在看栏

### ISSUE THREAD

**Issue by Boringc** [mythsman/hexo-douban#184]
问题描述: 点进去第一个显示的是正在看的 电影页面 基本上就是没有 电影一般也只有想看跟看过 很少有再看的选项
希望能有开关关闭掉在看选项

**Comment by mythsman** [comment]
可以看下 actions 字段，不想要的不加就行了。

**Comment by Boringc** [comment]
> 可以看下 actions 字段，不想要的不加就行了。

好的 谢谢
