### ISSUE TITLE
url error (caused by root directory)

### ISSUE THREAD

**Issue by tyrantqiao** [mythsman/hexo-douban#19]
my blog is saving at subdirectory '/Blog'
So when I click movie link, the URL would be 'name.github.io/movie', but actually, the URL should be 'name.github.io/Blog/movie'. How to fix this error?
(When I change the config to moive: /Blog/movie, that would only work successfully once, at the next time will be /Blog/Blog/moive)

**Comment by mythsman** [comment]
In fact, I once thought of this problem, but considering that many popular themes don't support putting site in a subdirectory, so I didn't take it carefully.
Emmm, seems it's time to consider it seriously ....

**Comment by mythsman** [comment]
Well , if you use yilia ,you just need to change the configuration in theme/yilia/_config.yml ,and set the value of 'root' to 'Blog' .

**Comment by tyrantqiao** [comment]
OK, I would try, thanks~

**Comment by mythsman** [comment]
@noodles1995 是不是用户id写错了。。。

**Comment by noodles1995** [comment]
@mythsman 只填写一个ID，还是要像这样https://www.douban.com/people/175507733/ 全部添加

**Comment by mythsman** [comment]
@noodles1995 只填ID就行了

**Comment by noodles1995** [comment]
@mythsman 谢谢 我再试试只填写ID 哈哈 应该没有 是我操作失误吧

**Comment by mythsman** [comment]
@noodles1995 OK，对了，有其他问题就开一个新的issue，不要在人家的issue下问哈。。。。这个issue就先关了。。。

**Comment by noodles1995** [comment]
@mythsman 好的 解决了 谢谢你
