### ISSUE TITLE
关于读书模块

### ISSUE THREAD

**Issue by qinyuanpei** [mythsman/hexo-douban#20]
最近发现读书模块生成的页面中，书籍封面无法正常加载，建议作者关注下这个问题。

**Comment by mythsman** [comment]
嗯？问题能复现一下么？我这边看的是没问题的。

**Comment by qinyuanpei** [comment]
你可以使用IE/Edge浏览器打开：https://qinyuanpei.github.io/books/，然后你就会发现书籍封面无法加载，经过测试Chrome没有这个问题，当然你可以忽略IE/Edge浏览器，我是说一下这个现象。

**Comment by qinyuanpei** [comment]
我并没有怪你的意思，我确定，希望作者不要生气啊 💯

**Comment by mythsman** [comment]
@qinyuanpei 蛤，没有没有，我还是挺谢谢大家能发现bug的 😄
