### ISSUE TITLE
一个小建议 关于插件开关

### ISSUE THREAD

**Issue by AlliotTech** [mythsman/hexo-douban#22]
感谢owner主如此棒的插件~ 
有个小建议 不知道好不好实现 
0.2.13已对网络环境不好的情况下进行了优化  能不能在hexo -s的时候加入一个参数使其不加载douban插件，这样就不会每次修改一些配置或者post的时候都重新获取一次豆瓣数据了(每次获取的时候都会卡一段时间  这段时间localhost:4000是不能访问的)。

**Comment by AlliotTech** [comment]
![qq 20180509155244](https://user-images.githubusercontent.com/24980252/39802638-1f7080b6-53a1-11e8-8de7-b7a7f9dcd6a1.png)

**Comment by AlliotTech** [comment]
我现在是hexo s前取消掉package.json中的douban.....hexo g的时候才加上去。。。

**Comment by mythsman** [comment]
研究了下感觉操作起来不太方便。。。你要是有好的解决方案倒可以提PR试试 :smile:

**Comment by mythsman** [comment]
1.0.1版本新增了一个命令功能，似乎可以简单解决这个问题。

**Comment by AlliotTech** [comment]
已回滚  2333   这阵子不折腾博客了。。。

**Comment by AlliotTech** [comment]
不行。。。我还是再测试一波吧。。。手痒
