### ISSUE TITLE
开启 busuanzi 后，生成的豆瓣读书、电影不能加载 busuanzi

### ISSUE THREAD

**Issue by dldylan** [mythsman/hexo-douban#25]
已经更新到 1.0.2 版本。

Hexo NexT主题（最新版本 Hexo 和最新版本 NexT）开启 busuanzi 后，生成的豆瓣读书、电影等页面不能加载 busuanzi，Chrome 提示：
```
Failed to load resource: the server responded with a status of 400 (Bad Request)
http://busuanzi.ibruce.info/busuanzi?jsonpCallback=BusuanziCallback_213324422534
```
而且导致生成的豆瓣读书、电影等页面的页脚中由 busuanz 统计的总访客数、总访问量无法显示。

**Comment by mythsman** [comment]
不知楼主的问题解决了没有，我看您的博客似乎已经没有问题了。

**Comment by dldylan** [comment]
@mythsman 你好，因为我现在关掉了 busuanzi 的网站访问数、访客数统计。如果开启 busuanzi 的统计，在豆瓣页页脚不会显示统计数字，但还是会显示比如「总访客数」这样的字样，不知道是不是因为 js 文件加载失败导致的。在其他页面，比如关于页、文章页，都是可以正常显示页脚的统计数据。

**Comment by mythsman** [comment]
研究了下busuanzi，他应该是根据referrer来判断主机来源的，而我之前为了能让IE现实“盗链”的图片将所有的referrer设置为了空，因此busuanzi失效。我权衡了下还是在1.0.3中支持了busuanzi，取消了对IE的支持。。。现在应该是可以的了。。。

**Comment by dldylan** [comment]
@mythsman 谢谢这么快更新！刚刚更新到 1.0.3 版本测试了，已经可以显示。IE 什么的不支持就不支持了吧……
