### ISSUE TITLE
图书能抓到 电影和游戏抓不到？

### ISSUE THREAD

**Issue by huaiweicheng** [mythsman/hexo-douban#29]
INFO  Start processing
INFO  105 books have been loaded in 2144 ms
INFO  0 movies have been loaded in 887 ms
INFO  0 games have been loaded in 920 ms
INFO  ---- START COPYING TAG CLOUD FILES ----
INFO  ---- END COPYING TAG CLOUD FILES ----
INFO  Generated: books/index.html
INFO  Generated: movies/index.html
INFO  Generated: games/index.html

**Comment by mythsman** [comment]
我这边试了下是可以的，你确认下是否插件是最新版本，以及确认下网络状况吧。

**Comment by mythsman** [comment]
如果是在墙外的服务器上执行的很有可能会抓不到。。。
