### ISSUE TITLE
分页处理

### ISSUE THREAD

**Issue by forvoid** [mythsman/hexo-douban#3]
好像没有做分页处理，我看了一下你的代码好像是一次遍历所以的数据然后进行静态渲染的，
```html
  do {
    res = callApi(config.douban.user, start);
    wish = wish.concat(res.wish);
    reading = reading.concat(res.reading);
    read = read.concat(res.read);
    start = res.start + res.count;
  } while ( start < res . total );
```
但是这样的话，如果数据请求过大，或者过多的化，感觉很容易出现下面这种情况
```bash
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: spawnSync C:\Program Files\nodejs\node.exe ETIMEDOUT
    at exports._errnoException (util.js:1018:11)
    at Object.spawnSync (child_process.js:459:20)
    at request (D:\blog\hexo\node_modules\urllib-sync\index.js:33:16)
    at callApi (D:\blog\hexo\node_modules\hexo-douban\lib\books-generator.js:25:13)
    at Hexo.module.exports (D:\blog\hexo\node_modules\hexo-douban\lib\books-generator.js:74:11)

```
就是说好像是因为等待返回数据同步的问题，这个在网络不好的环境下，generated成功的概率有点低。
###  目前我想到的方式
我感觉可以用js前端动态渲染的方式进行，就是去douban拿数据来渲染页面的方式，不知道可不可行

**Comment by mythsman** [comment]
关于前端请求，其实我之前也考虑过，不过这样动态请求有几点问题：
1.douban的api有每分钟调用的限制，如果并发的用户比较多，页面刷新频繁，既有可能造成api无法请求，也有可能被douban当成恶意爬虫
2.每次都调用与静态调用相比，显然直接拿静态的数据更快
3.每次靠客户端js去请求其实就是跨域访问了，大多浏览器都会禁止跨域。如果真要这样做，好像都是需要用一个cdn去中转，貌似比较麻烦。。。

关于分页，其实我还不知道怎么搞，最近忙着期末。而且我个人不太喜欢分页，感觉分页处理看的不舒服。我都挺像把archive的分页去掉了，但是把这个去掉的话首页也不分页了。。这就很难受。。。

关于你报的这个错，我之前也遇到过，我觉得问题应该不是等待同步的问题，因为我每一次请求可以获得100条信息，因此绝大多数情况下不会请求许多次，所以也就不存在同步异步的问题了。所以我觉得应该就是豆瓣api出现的问题，过一段时间应该就不会报错了吧。。。

**Comment by forvoid** [comment]
嗯嗯，我有可能没有表述清楚 我说的分页的意思是分段请求:smile:
1.并发用户较多的情况，感觉应该在乎前50或者前100的人看得多一点，后面的话会少很多
2.我同意你静态生成快的观点，这个和我提供的错误有一定关联，额我觉得这个错误的产生主要还是在于 网速🙈我今晚电脑网不太好成功率太低 哈哈大概10次生成成功了一次。
3.关于跨域请求 在非中心服务器 服务的情况下确实问题有点大，以我以前的处理方式都是通过后端修改请求头来给前端进行跨域请求的权利。

所以我觉得我还是要下去好好思考一下。
感谢你的回复
:+1:

**Comment by mythsman** [comment]
😌，后端改请求头？这是什么奇淫技巧，我明早起来学习一波😯

**Comment by forvoid** [comment]
跨域处理的直接方式我现在大概就了解两种
* jsonp
* cors 就是通过满足http协议来允许js跨域
这里给一个阮大神的blog http://www.ruanyifeng.com/blog/2016/04/cors.html

**Comment by mythsman** [comment]
多谢😊，我明天考完试学习学习😂

**Comment by forvoid** [comment]
good luck 
good night
👍⚽

**Comment by mythsman** [comment]
jsonp可行。。。cors受到豆瓣服务器的限制，好像搞不了。
不过反正也没打算这么搞^.^
