### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by jerryc127** [mythsman/hexo-douban#30]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。

设置了builtin参数为true，
hexo g 后，虽然会显示 XX movies have been loaded in xx ms
但是不会生成  movies/index.html
试了好多次都一样，打开Movies 显示不存在。最终还是靠hexo douban来解决

还有头部
![image](https://user-images.githubusercontent.com/16351105/43048635-65208c80-8e1d-11e8-9184-2bd72548114e.png)
能否自己修改名称？

**Comment by mythsman** [comment]
emm，可能是跟你装的其他插件有冲突吧，最近也发现过类似问题，所以才把hexo douban功能分离出来的。至于名称。。。目前只能自己去代码里改了。。。
