### ISSUE TITLE
404错误

### ISSUE THREAD

**Issue by gyl-coder** [mythsman/hexo-douban#31]
您好  我想请问一下   博客中添加的hexo-douban这个插件，在本地调试是没问题的   hexo clean    hexo g   hexo d  之后就404了                   

 我的插件装好之后，hexo douban b   生成的books是在站点目录下的public中 （每次hexo clean之后这个目录好像都会被删掉）    请问你们是如何处理这个问题的？？？？

**Comment by mythsman** [comment]
这是当然的啦，hexo clean的目的就是清除所有已生成的东西。这个应该不是问题吧，有问题的是你的操作流程，应该是hexo douban -> hexo generate -> hexo deploy 这样，没有特别的必要不需要hexo clean

**Comment by gyl-coder** [comment]
好的  谢谢  我再试试哈
