### ISSUE TITLE
Buildin 嵌入的问题

### ISSUE THREAD

**Issue by BetsyTang** [mythsman/hexo-douban#32]
您好，我Buildin设定为True了之后，生成页面任然未能嵌入`hexo g`和`hexo s`，确定为最新版本。

**Comment by BetsyTang** [comment]
![2018-09-22 09 06 46](https://user-images.githubusercontent.com/35840352/45911511-e4c67680-be46-11e8-89ea-0d9327c1cea2.png)
Genrate是成功了的，但是没有生成html文件

**Comment by mythsman** [comment]
我看下

**Comment by mythsman** [comment]
v1.0.6版本解决了builtin模式下的一些bug，你可以再试试看~

**Comment by BetsyTang** [comment]
好的，谢谢
