### ISSUE TITLE
豆瓣书单手机端页面无法显示图片

### ISSUE THREAD

**Issue by taohi** [mythsman/hexo-douban#33]
现在使用的是1.0.5版本，部署成功。但很奇怪生成的豆瓣读书页面，电脑端显示正常，而手机端图片不能加载。[书单页面](http://www.taohi.net/books/)

**Comment by mythsman** [comment]
这得等我置办了mac才能调一波。。。

**Comment by abelsu7** [comment]
> 这得等我置办了mac才能调一波。。。

hhh这就很尴尬。。

**Comment by b6514** [comment]
请问可以生成页面，但是却无法获取数据是怎么回事？[读书页面](https://bertliu.com/books)

**Comment by mythsman** [comment]
确认下豆瓣id有没有写对喽。。

**Comment by b6514** [comment]
没写错呀，试了好几遍还是不行[豆瓣](https://www.douban.com/people/bertliu/)

**Comment by mythsman** [comment]
@b6514 你再确认下使用的版本吧。。。我试了下你的id是没有问题的。。。

**Comment by b6514** [comment]
douban:
  user: https://www.douban.com/people/bertliu/
  builtin: false
  book:
    title: 'This is my book title'
    quote: 'This is my book quote'
  movie:
    title: 'This is my movie title'
    quote: 'This is my movie quote'
  game:
    title: 'This is my game title'
    quote: 'This is my game quote'
  timeout: 10000 
我又重新安装了最新版本的还是不行呀

**Comment by mythsman** [comment]
@b6514 user那一项填的是bertliu，不是url。。。

**Comment by b6514** [comment]
@mythsman 原来如此，可以了，感谢感谢！

**Comment by xjvr** [comment]
safari浏览器图片403。head加标签`<meta name="referrer" content="no-referrer">`就能解决了

**Comment by shuifengche** [comment]
> safari浏览器图片403。head加标签`<meta name="referrer" content="no-referrer">`就能解决了

感谢，这个方法成功了！

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
