### ISSUE TITLE
加引用来源和书的读后感链接

### ISSUE THREAD

**Issue by Latias94** [mythsman/hexo-douban#35]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。
## 加引用来源
我觉得既然可以加 quote，那就应该可以选择添加 quote 的 cite 引用来源。
例如：

> 仓促本身就是最要不得的态度。当你做某件事的时候，一旦想要求快，就表示你再也不关心它，而想去做别的事。
> _罗伯特 · M · 波西格 《禅与摩托车维修艺术》_

myblog\node_modules\hexo-douban\lib\templates\book.ejs
```ejs
<blockquote>
    <p><%- quote; %></p>
    <cite><%- quoteAuthor; %></cite>
</blockquote>
```
能加多个引用来源的支持就更好了

## 读后感链接 
因为插件目前好像只抓豆瓣的短评，而自己有时候会为书写读后感（书评），因此在书的页面下能否为一些书添加读后感（书评）的链接。
我觉得简单点的做法就是：在豆瓣某本书上评论里放读后感的链接，然后插件生成页面的时候能正则判断下，给链接加个 <a> 标签。
或者可以配置文件中加配置这种方式：
```yaml
bookid: 1234567
link: 'http://example.com' 
```

## Bug
buildIn 没效果，`hexo g` 会检查配置是否合法，但是不会重新生成新的 HTML 文件。

不知道作者对这样的新功能请求有什么看法😂

**Comment by mythsman** [comment]
哈哈，加引用来源的话其实quote本来就支持html语法的，又需要的话直接写html标签就行了，感觉没有太大的必要；读后感链接识别呢，我最近比较忙，看你是同行，你可以帮忙提一波pr喽；最后那个bug。。。我等会研究下。。。

**Comment by mythsman** [comment]
v1.0.6版本试图解决了这个bug，你可以再试试看

**Comment by Latias94** [comment]
官方源还没更新，不过自己按commit改了下能用，感谢。
两个新功能我就自己加在本地好了，正则用不好感觉会出很多新问题...

**Comment by imrhelloworld** [comment]
作者你好，可以出个javascript和css版本的吗？想使用在 Hugo 博客上。感谢！
