### ISSUE TITLE
默认标签页和分页条数

### ISSUE THREAD

**Issue by greedbob** [mythsman/hexo-douban#37]
请问可以增加两个功能吗，修改_config.yml便实现：
1.修改默认显示的标签页（如默认显示正在读的书，而非读过的书）。
2.另一个是修改自定义分页的条数（比如20条电影信息分页，而非10条）。

您做的非常好，非常感谢您！

**Comment by mythsman** [comment]
这个建议可行，过两天抽空弄下~

**Comment by greedbob** [comment]
谢谢您，辛苦了！
