### ISSUE TITLE
插件懒加载与hexo-lazyload-image冲突

### ISSUE THREAD

**Issue by AlliotTech** [mythsman/hexo-douban#38]
之前用的1.0.4正常，今天更新博客发现无法爬取了，于是更新到1.0.6，发现新特性懒加载与插件hexo-lazyload-image 冲突 建议在插件中添加一个开关选项
如图
![image](https://user-images.githubusercontent.com/24980252/47721240-a49ab500-dc8a-11e8-8e21-6f32b9e53154.png)

**Comment by mythsman** [comment]
很奇怪，这两个版本似乎没有改懒加载的逻辑哎。。。。

**Comment by AlliotTech** [comment]
看了一下commit。。。确实没有。。。 具体原因我再排查一下。。。  目前把hexo-lazyload-image关了。。。  其实感觉可以考虑添加一个懒加载的开关。。。
