### ISSUE TITLE
offline特性的问题

### ISSUE THREAD

**Issue by AlliotTech** [mythsman/hexo-douban#39]
之前提过的一个 issue，在 hexo-douban 没有与 `hexo s` 解耦的时候，在网络不好的情况下，会导致 `hexo s` 执行起来卡在爬取的阶段，现在解耦命令了，感觉那个特性可以去除掉了，因为在网络不好的情况下，由于这个特性，会需要多次执行 `hexo douban` 才能正常生成页面。。

**Comment by mythsman** [comment]
感觉可以留着吧，毕竟还有很多人是不用hexo s的~~

**Comment by AlliotTech** [comment]
(⊙o⊙)…  刚记起来timeout是有开关的，调大就好。hhh
