### ISSUE TITLE
No layout？

### ISSUE THREAD

**Issue by RingoTC** [mythsman/hexo-douban#4]
I install this plugin in your method.
But when I visit http://localhost:4000/books,I find that my terminal show me a warning which said _"WARN  No layout: books/index.html"_ 
How can I solve this problem?
Maybe I should develop this page by myself?

**Comment by mythsman** [comment]
it seems that you didn't generate the pages ,  please confirm your settings ,and then try "hexo g", then check whether you have 'movies/' and 'books/' directories....

**Comment by RingoTC** [comment]
The WARN
`INFO  Start processing
INFO  Files loaded in 3.12 s
WARN  No layout: books/index.html
WARN  No layout: movies/index.html
`

**Comment by mythsman** [comment]
let me see your  _config.yml ?

**Comment by RingoTC** [comment]
`# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Han Liao
subtitle:
description:
author: Han Liao
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://ringotc.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: apollo

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/RingoTC/ringotc.github.io.git

douban:
  user: hereshan
  book:
    title: 'This is my book title'
    quote: 'This is my book quote'
  movie:
    title: 'This is my movie title'
    quote: 'This is my movie quote'`

**Comment by RingoTC** [comment]
![default](https://user-images.githubusercontent.com/6525061/28622578-a1cd0d9a-7247-11e7-9e3e-4b442b74dd5e.png)

**Comment by mythsman** [comment]
i dont think anything is wrong... i would like to help you handle it  with your source code..

**Comment by RingoTC** [comment]
I had contact u with my outlook mailbox.
