### ISSUE TITLE
Mac和手机下单referrerpolicy不生效

### ISSUE THREAD

**Issue by CoderTonyChan** [mythsman/hexo-douban#41]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。

Mac和手机下单referrerpolicy不生效
Chrome正常

**Comment by mythsman** [comment]
没mac，求pr啊哈哈

**Comment by CoderTonyChan** [comment]
只有books下是这样 
movies和games都正常 
用Safari浏览 你的demos下的books也是不正常 其他正常

**Comment by CoderTonyChan** [comment]
加上<meta name="referrer" content="no-referrer" /> 这个就好了 safari下这个标签的优先度比较高的原因????

**Comment by dldylan** [comment]
@CoderTonyChan 

啊，十分感谢你的方法，成功解决了这个困扰已久的问题：豆瓣的图片无法在 macOS 和 iOS 中的 Safari 显示但是 Chrome 显示正常。

针对你说的如何在 Hexo 中配置这个标签，你可以把 
```html
<meta name="referrer" content="no-referrer" /> 
```
加入到 `.../themes/next/layout/_custom/head.swig` 中就可以了。
