### ISSUE TITLE
douban-loading.gif的问题

### ISSUE THREAD

**Issue by CoderTonyChan** [mythsman/hexo-douban#42]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。
建议去掉 douban-loading.gif 要么放进npm 要么就去掉 不然界面会报错

**Comment by mythsman** [comment]
为什么会报错。。。

**Comment by CoderTonyChan** [comment]
正常项目没这个图片吧

**Comment by mythsman** [comment]
@CoderTonyChan 包里有的

**Comment by CoderTonyChan** [comment]
现在才看到 但是打包也没拷贝进项目
![image](https://user-images.githubusercontent.com/16996753/50414258-7b903e00-084f-11e9-8a0e-9a7912140cc2.png)
是bug?

**Comment by mythsman** [comment]
你是不是改了什么。。。

**Comment by CoderTonyChan** [comment]
这么奇怪? 那如果没问题的话 就算了 
会不会如果默认目录下没assets 就会这样呢?
因为我资源文件夹叫 img

**Comment by mythsman** [comment]
1.0.7已升
