### ISSUE TITLE
页面无内容问题

### ISSUE THREAD

**Issue by littleheuer** [mythsman/hexo-douban#43]
1.0.7版本，执行hexo douban的时候能看到提示抓取到了数据，但是静态化和部署之后页面只有标题，没有其他任何内容，请问是什么情况。

**Comment by ArthurSmoke** [comment]
同遇到这个问题
---------------------------
hexo douban -b
INFO  Start processing
INFO  40 books have been loaded in 1058 ms
INFO  Generated: books/index.html
---------------------------
index页面内：
<main>
      
    </main>
---------------------------
"hexo-douban": "^1.0.8",

**Comment by zintown** [comment]
老哥，你这个问题解决了吗，我要也遇见了相同的问题

**Comment by zintown** [comment]
> 1.0.7版本，执行hexo douban的时候能看到提示抓取到了数据，但是静态化和部署之后页面只有标题，没有其他任何内容，请问是什么情况。

求教，我也遇见了这个问题，站点的_config.yml配置了，也hexo new page books$movies了，theme里的_config.yml也配置了，但是只有page books 内 index.md的内容，也就是只有标题

**Comment by mythsman** [comment]
@zintown 可能是跟主题不兼容吧。。。。
