### ISSUE TITLE
似乎不支持archer这个主题，hexo douban后报错

### ISSUE THREAD

**Issue by Boycottangent** [mythsman/hexo-douban#46]
使用[该主题](https://github.com/fi3ework/hexo-theme-archer)，打算把豆瓣的页面放到侧边栏，`hexo douban`的时候，显示
`Unhandled rejection TypeError: `和`Cannot read property 'format' of undefined`，节选报错如下图

<img width="575" alt="image" src="https://user-images.githubusercontent.com/23280916/53296509-56b64800-384b-11e9-9929-ef22ce77bde7.png">

报错太长，我也看不懂，希望开发者能尝试解决一下，谢谢

**Comment by mythsman** [comment]
试着关掉游戏页面的试试？

**Comment by Boycottangent** [comment]
> 试着关掉游戏页面的试试？

已经是关掉了的

**Comment by mythsman** [comment]
那就再这个主题的模板里面，对(page.xxx)这写东西加一个判空。。。

**Comment by Boycottangent** [comment]
小白不懂编程orz，感觉上是这个主题的问题？我去那里提一个issue吧，让他兼容一下douban插件吧

**Comment by mythsman** [comment]
你可以自己改一下post.ejs文件

**Comment by Boycottangent** [comment]
具体怎么改呢，能否详细说明一下我试试
可以的话帮忙看看文件在[这里](https://github.com/fi3ework/hexo-theme-archer/blob/master/layout/post.ejs)

**Comment by mythsman** [comment]
简单看一下ejs语法，在有 .format 方法的地方加一个if块就行了。。。

**Comment by Boycottangent** [comment]
我选择文章里不显示那些版权信息，目前暂时可以了，if 的问题我后续再解决
但是页面不显示封面，看了之前的issue一下是Safari的问题，希望尽快解决，谢谢

<img width="711" alt="image" src="https://user-images.githubusercontent.com/23280916/53297028-42c21480-3852-11e9-8daa-754a78255640.png">
