### ISSUE TITLE
iOS版微信中，图片不展示

### ISSUE THREAD

**Issue by kainy** [mythsman/hexo-douban#47]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。

貌似兼容性的问题，安卓里面OK。

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果这个feature还需要的话可以重新再反馈下，这个issue先关了。
