### ISSUE TITLE
如何解决microsoft edge和safari不显示图片bug?

### ISSUE THREAD

**Issue by jerryc127** [mythsman/hexo-douban#49]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。
如何解决microsoft edge和safari不显示图片bug?
![image](https://user-images.githubusercontent.com/16351105/54478944-067f4400-4853-11e9-849b-9e68f35c24b0.png)

**Comment by shuifengche** [comment]
请问你最后是怎么解决的呢？

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
