### ISSUE TITLE
1.0.8无法爬取书，电影和游戏正常

### ISSUE THREAD

**Issue by Sanarous** [mythsman/hexo-douban#50]
$ hexo douban                                                                   
INFO  Start processing                                                           
INFO  0 books have been loaded in 337 ms                                         
INFO  305 movies have been loaded in 13031 ms                                    
INFO  37 games have been loaded in 1837 ms                                       
INFO  Generated: books/index.html                                                
INFO  Generated: movies/index.html                                               
INFO  Generated: games/index.html
--
用的是hexo主题，不是显示问题，而是只有书爬不到。。。然后用了作者的user信息去爬，结果如上也是爬不到。。

**Comment by abelsu7** [comment]
同上。直接请求`books-generator.js`里面的接口，返回`invalid_apikey`的错误：

```json
{"msg":"invalid_apikey","code":104,"request":"GET \/v2\/book\/user\/abelsu7\/collections"}
```

**Comment by mythsman** [comment]
这。。我估摸着是douban加了鉴权。。。看上去很蛋疼。。。

**Comment by abelsu7** [comment]
`https://book.douban.com/people/<user>/wish`这个接口现在可用，应该可以像`movies-generator.js`和`games-generator.js`里那样直接解析 HTML 文档

**Comment by mythsman** [comment]
@abelsu7 有空我搞一搞，要不你来搞搞？

**Comment by abelsu7** [comment]
> @abelsu7 有空我搞一搞，要不你来搞搞？

我看下哈，会改的话就过来提`pull request`

**Comment by SwayYe** [comment]
同样的问题，希望大佬能早点解决，感谢！！

**Comment by mythsman** [comment]
刚尝试修复了下，试着升下1.1.0版本，如有问题及时反馈哈。
