### ISSUE TITLE
运行 hexo douban  时报错

### ISSUE THREAD

**Issue by kyriejoshua** [mythsman/hexo-douban#51]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。

**node v6.6.0
hexo-douban v1.1.0
hexo v3.7.1 v3.8.0**

![image](https://user-images.githubusercontent.com/16096736/54893576-63cd6200-4ef1-11e9-9701-82386de3cc1e.png)

查看是这里报错，`if(cookie.length==0){` 我把 cookie 的声明放在函数内就不报错了。但无法抓取到任何书或者电影。

应该是最近的更新导致的，之前在 v1.0.5 是 ok 的。

**Comment by mythsman** [comment]
虽然我这边没有复现这个问题，不过我还是尝试改了一下，升一下1.1.2试试。

**Comment by kyriejoshua** [comment]
@mythsman 非常感谢。更新后运行不报错了。不过很奇怪还是爬不到书或者电影。

![image](https://user-images.githubusercontent.com/16096736/54898790-80c15f80-4f08-11e9-951e-c65e32023b5c.png)

这个我不确定是我网络不好还是其他问题。

**Comment by mythsman** [comment]
@kyriejoshua 我昨天测的时候发现的是读书的已读页面如果不加cookie是会报403的，所以我先访问的其他接口，拿了cookie再访问的已读页面。。。

**Comment by kyriejoshua** [comment]
好的，了解。。
