### ISSUE TITLE
不能自定义生成页面的样式吗，比如我的主题顶上有大图

### ISSUE THREAD

**Issue by ourongxing** [mythsman/hexo-douban#55]

**Comment by mythsman** [comment]
可能不是很兼容。。。

**Comment by ourongxing** [comment]
> 可能不是很兼容。。。

那能告诉我在哪自定义吗

**Comment by ourongxing** [comment]
> 可能不是很兼容。。。

我已经改好了，这个插件我真的很喜欢

**Comment by mythsman** [comment]
> > 可能不是很兼容。。。
> 
> 我已经改好了，这个插件我真的很喜欢

厉害了。。。。

**Comment by nhbgfyjnfg** [comment]
> > 可能不是很兼容。。。
> 
> 我已经改好了，这个插件我真的很喜欢

请问大佬，是怎么改的呢？
