### ISSUE TITLE
不能爬取内容

### ISSUE THREAD

**Issue by ourongxing** [mythsman/hexo-douban#56]
根据我多次测试，为了排除个人原因，我新建了一个hexo博客，使用默认设置，都不能爬取内容
是不是已经失效了

**Comment by mythsman** [comment]
我试了下还可以啊。。。。

**Comment by ourongxing** [comment]
![image](https://user-images.githubusercontent.com/48356807/61020576-d6931800-a3d0-11e9-8567-8e51aff256cf.png)
我新建了一个hexo博客，使用默认设置，完全没动其他地方

**Comment by ourongxing** [comment]
> 我试了下还可以啊。。。。是不是比较慢。。。

![image](https://user-images.githubusercontent.com/48356807/61020655-0b9f6a80-a3d1-11e9-88f8-8f5e94e9406d.png)

我新建了一个hexo博客，使用默认设置，完全没动其他地方

**Comment by mythsman** [comment]
user 名字配错了？

**Comment by ourongxing** [comment]
> user 名字配错了？看下你的_config.yml里的配置。。

![image](https://user-images.githubusercontent.com/48356807/61021697-2673de00-a3d5-11e9-837f-0a7893112cbd.png)

**Comment by ourongxing** [comment]
> user 名字配错了？看下你的_config.yml里的配置。。

之前是可以的，就今天突然就不行了

**Comment by mythsman** [comment]
我试了下是可以的。。。可能是你的版本老了，升一下最新版本吧。。

**Comment by ourongxing** [comment]
> 我试了下是可以的。。。可能是你的版本老了，升一下最新版本吧。。

我是npm重新安装的呀

**Comment by mythsman** [comment]
手动指定一下最新版本吧。。。

**Comment by ourongxing** [comment]
> 手动指定一下最新版本吧。。。

![image](https://user-images.githubusercontent.com/48356807/61022456-6ab4ad80-a3d8-11e9-8fa3-d0d6ea22c796.png)
有点无解了

**Comment by ourongxing** [comment]
> 手动指定一下最新版本吧。。。

我找到原因了，原来是这个移动宽带的锅，我手机开热点就可以了
