### ISSUE TITLE
1.1.3版本hexo douban -b结果如下

### ISSUE THREAD

**Issue by taohi** [mythsman/hexo-douban#57]
hexo douban -b结果：
```
INFO  0 books have been loaded in 3066 ms, because you are offline or your network is bad
INFO  0 movies have been loaded in 3041 ms, because you are offline or your network is bad
INFO  Generated: books/index.html
```
timeout配置为  `timeout: 50000`

请问这个怎么解决一下？

**Comment by taohi** [comment]
网络是好的，用浏览器可以正常打开豆瓣

**Comment by mythsman** [comment]
可能是账号中了风控。。。你可以退出账号后访问 www.douban.com/people/{your id} ，如果提示要登录，那就说明是中了风控了。。。

**Comment by taohi** [comment]
> 可能是账号中了风控。。。你可以退出账号后访问 [www.douban.com/people/{your](http://www.douban.com/people/%7Byour) id} ，如果提示要登录，那就说明是中了风控了。。。

试了下，没有中风控。id：taohi。我等一个月再看看。thanks

**Comment by zwz1437** [comment]
尝试使用别的nodejs版本，在本地使用12.18.0是正常的，用travis ci进行部署使用的nodejs版本为stable，build passing后不能正常显示，数据都是0，修改nodejs为12.18.0后重新build就正常了

**Comment by ls19970727** [comment]
> 尝试使用别的nodejs版本，在本地使用12.18.0是正常的，用travis ci进行部署使用的nodejs版本为stable，build passing后不能正常显示，数据都是0，修改nodejs为12.18.0后重新build就正常了

哇，还真是这个问题，找了好久，之前用的14.xx.xx版本的不行，卸载nodejs，现在安装了12.18.1解决了。感谢大佬！

**Comment by shenmingyu** [comment]
> 可能是账号中了风控。。。你可以退出账号后访问 [www.douban.com/people/{your](http://www.douban.com/people/%7Byour) id} ，如果提示要登录，那就说明是中了风控了。。。

中风控是什么意思呀，我的好像就是这个情况，能请教下怎么搞嘛

**Comment by Plaudern** [comment]
> 可能是账号中了风控。。。你可以退出账号后访问 [www.douban.com/people/{your](http://www.douban.com/people/%7Byour) id} ，如果提示要登录，那就说明是中了风控了。。。

你好中了风控怎么处理了

**Comment by theingz** [comment]
> 尝试使用别的nodejs版本，在本地使用12.18.0是正常的，用travis ci进行部署使用的nodejs版本为stable，build passing后不能正常显示，数据都是0，修改nodejs为12.18.0后重新build就正常了

使用此方法得到了解决，用nvm 切换一些nodejs版本为V12就可以了，感谢大佬，虽然不知道是啥原因。

**Comment by OctopusLian** [comment]
> > 尝试使用别的nodejs版本，在本地使用12.18.0是正常的，用travis ci进行部署使用的nodejs版本为stable，build passing后不能正常显示，数据都是0，修改nodejs为12.18.0后重新build就正常了
> 
> 使用此方法得到了解决，用nvm 切换一些nodejs版本为V12就可以了，感谢大佬，虽然不知道是啥原因。

我切到了12.18.0，不得行，请问你是切到了哪个版本号呢？

**Comment by jianyiblog** [comment]
我的主题不支持低版本node，怎么办

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
