### ISSUE TITLE
点击链接会打开一个空白页

### ISSUE THREAD

**Issue by L1cardo** [mythsman/hexo-douban#58]
点击'在读'，'想读'，'已读'，这些按钮的时候会打开一个空白页。

我的博客地址是[这个](https://licardo.cn)，能看一下吗？

**Comment by mythsman** [comment]
把标签里的`target='_blank'`移除就好了。

**Comment by L1cardo** [comment]
我特地测试了一下，手机端不会出现这个问题。电脑端Safari也不会出现，只有电脑端Chrome有这个问题。

**Comment by L1cardo** [comment]
还有一个问题：手机端不管什么浏览器都没有图片加载。电脑端Safari没有图片加载。

**Comment by mythsman** [comment]
哎。。浏览器兼容的事情太让人头大了。。。

**Comment by L1cardo** [comment]
emmmm这个确实是个问题
但是chrome天下第一不支持不太好吧

**Comment by L1cardo** [comment]
`target='_blank'`的生成逻辑是什么？是所有的链接都会生成吗?

**Comment by L1cardo** [comment]
不能做一下调整吗？
在这些参数前面不要`target='_blank'`

**Comment by mythsman** [comment]
我这边是没有加的，应当是你用了什么插件，会自动把非本站的链接自动添加 target='_blank'。。。

**Comment by L1cardo** [comment]
我`hexo douban`生成的文件里面没有`target='_blank'`，但是在Chrome里面打开就自动给我加上了！

![截屏2019-09-18下午11 08 37](https://user-images.githubusercontent.com/33802186/65160973-5ab8ea00-da69-11e9-8fb9-af68c6afb459.png)
![截屏2019-09-18下午11 07 36](https://user-images.githubusercontent.com/33802186/65160977-5bea1700-da69-11e9-8f78-0445d4ad2c55.png)

**Comment by L1cardo** [comment]
电脑qq浏览器没问题，但是Chrome始终不行

**Comment by FraserYu** [comment]
> 电脑qq浏览器没问题，但是Chrome始终不行

同样的问题

**Comment by EstralleTommm** [comment]
+1

**Comment by jerryc127** [comment]
Hexo 4.0.0的問題
https://github.com/hexojs/hexo/issues/3796

**Comment by shuifengche** [comment]
同样有这个问题，把hexo降低至3.9.0版本就好了。
