### ISSUE TITLE
关于将builtin设置为true或者false的问题

### ISSUE THREAD

**Issue by mikuwife** [mythsman/hexo-douban#59]
我想问下设置成true的时候，page页面设置自定义top_img图片是无效的
设置成false的时候，page页面top_img图片有效但是书单，电影，和游戏就显示不出来
--以上，请教该怎么设置

**Comment by mythsman** [comment]
@Nkn-Miku 不知道你的自定义top_img是怎么处理的，感觉应该是跟你的用法不是很兼容。。。

**Comment by Nkn-Miku** [comment]
解决了，主题的链接改掉就行了

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
