### ISSUE TITLE
up主，豆瓣只能显示默认内容，点击不会切换

### ISSUE THREAD

**Issue by itgoyo** [mythsman/hexo-douban#6]
你好，这款插件确实做得很好，但是用在项目中的时候我发现两个小问题，就是豆瓣书籍部分只能显示在读，要是我点击已读或者想读，电影部分也是这样子，只能显示默认的不能进行切换，请问后面还会再优化吗

**Comment by mythsman** [comment]
你的意思是希望能够配置默认标签页么？我有空的时候就搞搞呗，你也可以改好提过来喽0.0

**Comment by itgoyo** [comment]
@mythsman 提供配置更改项也是一个不错的选择，现在主要问题是，在读、已度，这两部分点击是不能切换的，如果默认是在读，你点已读的话，就自动跳转到一个空白页面，我测试我的blog，和你的是一个情况。我上网查查倒弄倒弄，我是搞移动端的，不是很熟悉网站这边的开发，:smile

**Comment by mythsman** [comment]
不对啊，你说的这个问题我怎么没有遇到呢？应该是可以选不同的标签的啊
