### ISSUE TITLE
关于安装时 的报错$ npm install hexo-douban --save

### ISSUE THREAD

**Issue by wwm973** [mythsman/hexo-douban#60]
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
 

望解答 万分感谢！

**Comment by wwm973** [comment]
已解决，静静的等待它安装好就可以了

**Comment by mythsman** [comment]
😄
