### ISSUE TITLE
在iOS、macOS平台出现的封面无法获取的问题

### ISSUE THREAD

**Issue by eiinu** [mythsman/hexo-douban#61]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。

在Safari浏览器上无法显示电影、书籍等的封面图片，显示403错误。
在iOS手机上的微信、QQ等软件内置浏览器同样无法显示。
在[另一个issues](https://github.com/mythsman/hexo-douban/issues/33)中有人提到了，在生成的movies/books/games的html文件中head部分增加`<meta name="referrer" content="no-referrer">`标签，亲测有效。
希望可以在下一版本中添加。

**Comment by 49092095** [comment]
附议！

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
