### ISSUE TITLE
配置好之后点击/blog/movies/，会默认自动新弹到一个about:blank#blocked的页面，原页面显示正常，不知道是什么情况。

### ISSUE THREAD

**Issue by RalstonLiu** [mythsman/hexo-douban#62]
配置好之后点击/blog/movies/，会默认自动新弹到一个about:blank#blocked的页面，原页面显示正常，不知道是什么情况。

**Comment by SimpCosm** [comment]
复议，我也是有这个情况。

使用的浏览器为 Chrome

**Comment by Insomnia1437** [comment]
同样情况，hexo v4.0.0, Next v7.7.0, douban v1.1.3。
Chomre上是弹窗，换了IE是无法显示图片。

**Comment by lawzizhuang** [comment]
附议。

我也遇到这个情况。

Chrome v80，Hexo 4.2.0， hexo-douban 1.13

**Comment by nagenanhai** [comment]
> 复议，我也是有这个情况。
> 
> 使用的浏览器为 Chrome

附议。我的也是。hexo4.0.0，douban1.1.3，请问你们都解决了么。。

**Comment by nagenanhai** [comment]
> 附议。
> 
> 我也遇到这个情况。
> 
> Chrome v80，Hexo 4.2.0， hexo-douban 1.13

附议。我的也是。hexo4.0.0，douban1.1.3，请问你们都解决了么。。

**Comment by nagenanhai** [comment]
> 同样情况，hexo v4.0.0, Next v7.7.0, douban v1.1.3。
> Chomre上是弹窗，换了IE是无法显示图片。

附议。我的也是。hexo4.0.0，douban1.1.3，请问你们都解决了么。。

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果这个feature还需要的话可以重新再反馈下，这个issue先关了。
