### ISSUE TITLE
无法获取信息

### ISSUE THREAD

**Issue by jiyangzhao** [mythsman/hexo-douban#64]
因为每次生成页面的时候都要读取一次记录，导致读取次数太多了，现在无法读取到图书和电影信息了。（大概是被豆瓣限制了）
> INFO  0 books have been loaded in 3256 ms
INFO  0 movies have been loaded in 3246 ms

有没有办法设置手动读取数据（如果直接设置false，每次都会把之前的页面删除），以及现在没法读取的问题怎么解决？

**Comment by JieYueCoding** [comment]
过一天之后又可以读取到了

**Comment by crownz-sec** [comment]
原来是自己生成太多次，被限流了

**Comment by luoguliziheng** [comment]
qwq我也读不到啊

**Comment by asdf2014** [comment]
感觉没几次就出现限流了，这个阈值谁清楚吗？

**Comment by AlliotTech** [comment]
豆瓣的反爬虫机制。。  会封禁IP 一天（具体时间不清楚） 一般第二天就正常了..

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
