### ISSUE TITLE
手机上查看网页，封面图片不能显示，能不能将封面图片缓存到下来呐

### ISSUE THREAD

**Issue by xinxingli** [mythsman/hexo-douban#66]
图片防盗链了，能不能将图片缓存到本地呐？

**Comment by asdf2014** [comment]
+1

**Comment by asdf2014** [comment]
原来是不识别 referrerPolicy 导致的，加一个 meta 头就好了

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果这个feature还需要的话可以重新再反馈下，这个issue先关了。
