### ISSUE TITLE
无法正常显示中文“在读”|“想看”|“已读”，只显示英文的情况。同时无法进行翻页切换。

### ISSUE THREAD

**Issue by Liaozhebin** [mythsman/hexo-douban#68]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。

在部署豆瓣的时候，出现了无法正常显示“在读”|“想看”|“已读”，只显示英文的情况。同时无法进行翻页切换。
不知大家是否遇到过这个问题，想请大家帮我看看，https://592592.xyz/books/
如图：![](https://gitee.com/liaozhebin/imagebed/raw/master/images/douban.webp)

**Comment by Liaozhebin** [comment]
补充：可能第一次打开能正常显示选项卡，刷新后会出现上面这样的现象。
环境：hexo4.2  next7.7.2

**Comment by Liaozhebin** [comment]
### 问题已经解决：前来反馈，感谢 [小丁博客](https://tding.top/archives/c7ba3a41.html)@dta0502 提供的减法调试的想法：
#### 豆瓣页面显示英文问题：
通过减法调试，逐渐卸载插件和删除配置文件，最后发现原来是我修改了Hexo配置目录下的语言选项。把原来的 `zh-CN` 修改为了  `zh-Customize` ,  这个 `zh-Customize` 是我自己修改 `next/language/zh-CN` 后的文件，其中添加了一些中英文双语显示，没想到 `豆瓣插件` 居然会通过 HEXO配置文件的语言 来生成不同语言的静态页面，而我设置的语言没有被匹配成功，估计默认生成了国际语言 `英文`。
#### 豆瓣页面没有评分的问题
这个问题通过一番查看，发现是因为我在豆瓣主页添加的 `看过` 电影没有进行 `打分和评价` 造成的，在豆瓣这边打分评价之后，博客的豆瓣页面就有显示了。
同时呢：在豆瓣这边虽然 `在看|在读` 也是可以打分的，但是在博客豆瓣这边，`在读| 在看` 状态的条目，是不会显示评分评价的。 
这个显示细节小丁也可以再观察一下自己的哦。

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
