### ISSUE TITLE
执行hexo g命令后报错

### ISSUE THREAD

**Issue by qinyuanpei** [mythsman/hexo-douban#7]
在安装插件以后，执行hexo g命令生成页面时报错，根据错误信息推断是Promise报错，请问在这种情况下我应该怎么做呢？

**Comment by mythsman** [comment]
估计是网络不畅或者是请求的东西太多了，相应比较慢。。。等网络好一点应该就行了。。。

**Comment by mythsman** [comment]
添加了个timeout的设置，如果超时了就把timeout的值设置大一点。。。比如50000。。。
