### ISSUE TITLE
望去掉多余的target="_blank"

### ISSUE THREAD

**Issue by arandintday** [mythsman/hexo-douban#70]
在切换已读，想读，未读和翻页时会自动弹出一个空白标签页。修改ejs文件去掉target="_blank"后生成页面仍然会跳转，F12检查页面元素仍然存在target="_blank"，建议修复

**Comment by arandintday** [comment]
已自行解决，原来是我用的主题会自动把页面内的超链接添加一个Attribute

**Comment by Brikarl** [comment]
我也是这种情况，想问一下怎么解决的~

Chrome v81，Hexo 4.2.0

**Comment by arandintday** [comment]
> 我也是这种情况，想问一下怎么解决的~
> 
> Chrome v81，Hexo 4.2.0

你的主题是什么？如果也是matery的话去themes/hexo-themes-matery/source/js里找到matery.js，打开，把
$('#articleContent a').attr('target', '_blank');
改成
$('#articleContent a').attr('target', '_self');
就可以了，缺点是以后打开页面内的链接会直接跳转而不是在新标签页打开
