### ISSUE TITLE
好像又爬取不到了？

### ISSUE THREAD

**Issue by DSzhongweizi** [mythsman/hexo-douban#71]
hexo douban没用了，爬取为0，开启builtin后的hexo g 和 s也没用，都是0条

**Comment by Amumu547426** [comment]
请问问题解决了么，我这里也爬不到

**Comment by BitHachi** [comment]
我也是

**Comment by kiwiflydream** [comment]
我也遇到了，切个ip就好了，应该是被豆瓣风控了

**Comment by Amumu547426** [comment]
切ip也不行啊，INFO  0 movies have been loaded in 1724 ms, because you are offline or your network is bad每次都是这种错误

**Comment by hayschan** [comment]
解决了吗？

**Comment by DSzhongweizi** [comment]
可能网络问题吧，有时候就会这样

**Comment by weilain** [comment]
@Amumu547426  遇到一样的状况
INFO  0 books have been loaded in 987 ms, because you are offline or your network is bad
INFO  0 movies have been loaded in 1040 ms, because you are offline or your network is bad
更新换node版本就好了，我之前v12.18.0 就是更新了下node v15.5.1 ，抓取不到了，退回之前版本就可以了

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
