### ISSUE TITLE
生成的页面中没有信息

### ISSUE THREAD

**Issue by wjinfeng** [mythsman/hexo-douban#74]
可以爬取到，但是生成的页面中没有信息

**Comment by cn-Wziv** [comment]
INFO  12 books have been loaded in 3271 ms                                      
 INFO  4 movies have been loaded in 2167 ms
--
生成的界面中是空白的

**Comment by cn-Wziv** [comment]
查到问题了   是主题的原因    我用的是主题叫AD   有相同问题的可以注意

**Comment by cooper1x** [comment]
@cn-Wziv 主题是什么问题呢，是哪里冲突了吗？我也遇到了页面没有信息的问题。

**Comment by cn-Wziv** [comment]
哈哈，可能是我没有描述清楚，我的理解是某些主题不支持该插件，我最后换了个主题

**Comment by cn-Wziv** [comment]
@cooper1x 哈哈，可能是我没有描述清楚，我的理解是某些主题不支持该插件，我最后换了个主题

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
