### ISSUE TITLE
typography 主题中，无法在首页显示豆瓣页面入口

### ISSUE THREAD

**Issue by CalvinoShaw** [mythsman/hexo-douban#76]
使用了最近的版本
用的是 typography 这个主题 https://github.com/SumiMakito/hexo-theme-typography

按步骤逐步执行了，本地 localhost 预览的时候，首页的目录栏没有【读书】【电影】等链接入口，
但是直接在地址栏输 /books 等，可以跳转到对应页面和显示

<img width="914" alt="企业微信截图_1599733000770" src="https://user-images.githubusercontent.com/17917945/92716775-d81fed80-f391-11ea-95c1-7bc301c69252.png">

**Comment by CalvinoShaw** [comment]
问题已经解决，需要自己另行 `hexo new page books ` 生成对应的页面

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
