### ISSUE TITLE
电影页面没有电影的缩略图

### ISSUE THREAD

**Issue by thuxx** [mythsman/hexo-douban#8]
[page](https://thuxx.github.io/movies/)
以前有的，现在怎么回事呢？
书籍页面有缩略图

**Comment by thuxx** [comment]
检查了网页源代码 应该是生成了图片链接 为什么不显示呢？ IE 火狐 谷歌都没用 是因为影片太多了？

**Comment by mythsman** [comment]
我也刚发现。。。。我研究看看。。。

**Comment by thuxx** [comment]
……那有什么解决方法吗  我是小白  这个插件确实挺不错的所以来问问  为什么书籍有图呢

**Comment by mythsman** [comment]
大概是豆瓣觉得咱么这种行为侵犯了他们的资源，所以做了一些处理，你看console里返回一堆403.。。

**Comment by thuxx** [comment]
啊好吧 暂时只能这样吧 ==

**Comment by mythsman** [comment]
过两天有空了就得花点时间对付下。。。

**Comment by thuxx** [comment]
麻烦啦 静候佳音

**Comment by mythsman** [comment]
带晚搞了下，现在应该可以了，npm update hexo-douban即可升级到0.2.2版本。。。

**Comment by itgoyo** [comment]
升级0.2.2之后，已经可以预览缩略图。

**Comment by mythsman** [comment]
其实就是加了一个免费代理。。。期待这个代理不会挂吧。。。。。。

**Comment by thuxx** [comment]
谢啦 已恢复
