### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lanlandebaiyun** [mythsman/hexo-douban#81]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。
当我切换想看、已看的时候会出来一个空白的页面
about:blank
这是哪里有问题啊

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果有问题可以重新再反馈下，这个issue先关了。
