### ISSUE TITLE
音乐tag可用吗？

### ISSUE THREAD

**Issue by kelecn** [mythsman/hexo-douban#82]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。
我这边改成音乐tag，没有显示，是不是没有爬取music tag？

**Comment by W4J1e** [comment]
请问你电影和读书能正常爬到数据吗？

**Comment by kelecn** [comment]
电影和阅读都能正常爬到的qwq

**Comment by kelecn** [comment]
> 请问你电影和读书能正常爬到数据吗？
电影和阅读完全正常爬到的qwq

**Comment by W4J1e** [comment]
> > 请问你电影和读书能正常爬到数据吗？
> > 电影和阅读完全正常爬到的qwq

我用这个插件爬不到数据QZQ，所以我用了另一个，但是样式不太好看，想尝试着改改。

**Comment by kelecn** [comment]
> > > 请问你电影和读书能正常爬到数据吗？
> > > 电影和阅读完全正常爬到的qwq
> 
> 我用这个插件爬不到数据QZQ，所以我用了另一个，但是样式不太好看，想尝试着改改。
好呀，你用的哪一个？啊？😁

**Comment by mythsman** [comment]
用的人不多，暂时不考虑支持。
