### ISSUE TITLE
无法爬取

### ISSUE THREAD

**Issue by Giagoo** [mythsman/hexo-douban#83]
刚开始安装可以爬取，过了几个小时之后就爬取不到了，是ip被封了吗？有什么解决方法吗？

**Comment by weilain** [comment]
INFO  0 books have been loaded in 987 ms, because you are offline or your network is bad
INFO  0 movies have been loaded in 1040 ms, because you are offline or your network is bad

我这边也是

**Comment by weilain** [comment]
我把node 版本回退到v12.18.1 可以正常使用， 我只是做了 node版本更新，出现次问题

**Comment by Giagoo** [comment]
> 我把node 版本回退到v12.18.1 可以正常使用， 我只是做了 node版本更新，出现次问题

我回退了也没用，但是我找到原因了，应该是太频繁爬取导致ip被封了，今天已经好了，解封了

**Comment by Giagoo** [comment]
已解决
