### ISSUE TITLE
douban电影数据爬取不到

### ISSUE THREAD

**Issue by Accelerator086** [mythsman/hexo-douban#84]
如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。

---

```
INFO  Start processing
INFO  0 movies have been loaded in 1056 ms, because you are offline or your network is bad
```
网络情况一切正常，所有包都更新到最新版本，但是出现了同样的问题。
隔壁 `hexo-bilibili-bangumi` 采用相似的源码成功爬取Bilibili番剧信息，但是这里爬取不到douban数据。

#83 #71 #77 #81 #78 #75 #73 #56

**Comment by EmilyBear** [comment]
只有Node.js版本是12.x才能爬到数据······

**Comment by cyrus0w** [comment]
最后解决了吗？

**Comment by cyrus0w** [comment]
> 如果你在使用中发现了问题，首先请确保你使用的版本是最新的版本，最新的更新记录可以从[这里](https://github.com/mythsman/hexo-douban#user-content-%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)查看。
> 
> ```
> INFO  Start processing
> INFO  0 movies have been loaded in 1056 ms, because you are offline or your network is bad
> ```
> 
> 网络情况一切正常，所有包都更新到最新版本，但是出现了同样的问题。
> 隔壁 `hexo-bilibili-bangumi` 采用相似的源码成功爬取Bilibili番剧信息，但是这里爬取不到douban数据。
> 
> #83 #71 #77 #81 #78 #75 #73 #56

最后解决了吗？

**Comment by OctopusLian** [comment]
同样的问题，已经是`1.1.3`最新版本

**Comment by Accelerator086** [comment]
您好，您发送的邮件我已收到，我会尽快处理回复的。谢谢您！祝您生活愉快！
Hello. This is an automatic reply, confirming that your e-mail was received. Thank you and have a good time！   张一浩Andy Zhang

**Comment by jianyiblog** [comment]
node版本问题，怎么解决

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下。

**Comment by Accelerator086** [comment]
已经解决了，升级新版本操作即可，非常感谢！！！
