### ISSUE TITLE
和PJAX冲突，无法加载图片和样式

### ISSUE THREAD

**Issue by Alobal** [mythsman/hexo-douban#85]
![image](https://user-images.githubusercontent.com/35487993/110240064-197e0800-7f85-11eb-969d-e7eb18f2d26a.png)

**Comment by chen-coding** [comment]
同样情况，有解决方法吗

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下，如果还有问题，可以重新反馈下。
