### ISSUE TITLE
图片错位

### ISSUE THREAD

**Issue by qinyuanpei** [mythsman/hexo-douban#9]
在indigo主题下生成的页面图片会发生错位现象，而且一定几率Promise会报错。

**Comment by mythsman** [comment]
没适配过这个主题。。。有空搞下吧。。promise报错很大可能网络不好，请求的太快。。。。。。

**Comment by mythsman** [comment]
@qinyuanpei 我试了下发现indigo主题也是完美适配的，如果有问题的话先npm update把插件更新到最新版本试试看呢。

**Comment by qinyuanpei** [comment]
你可以访问这个页面，https://qinyuanpei.github.io/books/，我确认这应该是有样式问题的，

**Comment by qinyuanpei** [comment]
你可以访问这个页面，[https://qinyuanpei.github.io/books/](https://qinyuanpei.github.io/books/)，我觉得这里样式应该是有问题的

**Comment by mythsman** [comment]
我看了下，应该是你自己改了css或者是layout，你看下图片img标签对应的css，你这里是继承了".post-content img"，而正常情况下应该是继承了".page-content img"。。。我这边默认的layout应该是page。。。

**Comment by qinyuanpei** [comment]
所以你的意思是说，我只要将这里的layout设置为page即可，好的，我试试看
