### ISSUE TITLE
[compatibility bug]: Unhandled rejection TypeError 

### ISSUE THREAD

**Issue by Crazyokd** [mythsman/hexo-douban#93]
具体错误描述见[https://github.com/HCLonely/hexo-bilibili-bangumi/issues/166](https://github.com/HCLonely/hexo-bilibili-bangumi/issues/166)

希望作者也能做个适配。

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下。
