### ISSUE TITLE
爬不到数据

### ISSUE THREAD

**Issue by SLOWDOWNO** [mythsman/hexo-douban#97]
在读(0),已读(0),想读(0)

**Comment by SLOWDOWNO** [comment]
INFO  0 books have been loaded in 3 ms, because you are offline or your network is bad
INFO  0 movies have been loaded in 1 ms, because you are offline or your network is bad

**Comment by icheer** [comment]
Hi，感谢作者提供的豆瓣插件，我是多年的老用户了。
冒昧基于作者的1.1.3版本魔改了一版[1.1.3plus](https://github.com/icheer/hexo-douban#readme)（因为我服务器直接抓取豆瓣好像还挺稳定的，后续基于公用服务抓取豆瓣反而抓不到）

```json
"dependencies": {
  ...
  "hexo-douban": "git+https://github.com/icheer/hexo-douban.git"
  ...
}
```
这样修改package.json，（最好删掉node_modules/hexo-douban目录），然后npm install一下（如果是linux服务器，请确保已经安装过git了 yum install git -y），就可以通过hexo douban -h命令抓取豆瓣信息了。
增加了豆瓣音乐的支持，详见[readme](https://github.com/icheer/hexo-douban#readme)文档。
这是我一直期盼的音乐页面demo： [http://icheer.me/albums/](http://icheer.me/albums/)

```shell
[root@VM-4-5-centos icheerme]# hexo douban -h
INFO  Start processing
想读: 64
在读: 34
读过: 98
INFO  196 books have been loaded in 18522 ms
想看: 45
在看: 11
看过: 260
INFO  316 movies have been loaded in 16623 ms
想听: 0
在听: 0
听过: 0
INFO  0 albums have been loaded in 20801 ms, because you are offline or your network is bad
想玩: 1
在玩: 2
玩过: 24
INFO  27 games have been loaded in 2015 ms
[root@VM-4-5-centos icheerme]#
[root@VM-4-5-centos icheerme]# 有时候不太顺利抓取到0条，可能因为翻页抓得太频繁了，可能被限流了。。过一会再单独抓一下它吧。。^C
[root@VM-4-5-centos icheerme]#
[root@VM-4-5-centos icheerme]# hexo douban -a
INFO  Start processing
想听: 25
在听: 28
听过: 68
INFO  121 albums have been loaded in5172 ms
```
