### ISSUE TITLE
🆘为什么使用node16.18.0版本无法拉取数据，使用低版本就可以？

### ISSUE THREAD

**Issue by jianyiblog** [mythsman/hexo-douban#98]
🆘🆘🆘能不能优化一下node版本问题啊大佬，我用低版本node没办法使用我现在的hexo主题啊

**Comment by mythsman** [comment]
工作比较忙，很久前写的玩具，好久不维护了。原先的逻辑架构上不太合理，也遗留了太多issue没处理，维护不过来了。

计划这段时间重写一把，使用方式会有很大改动，不过生成页面会更加快捷稳定，也会支持多种博客系统。

**Comment by jianyiblog** [comment]
> 工作比较，现在之前写的东西久久没有维护了。不过，很好的业务架构上来处理了，也没有维护过任何问题，，
> 
> 使用方式计划时间段，会立即快速生成，但是会支持多个博客系统。

好的感谢大佬，期待更新

**Comment by mythsman** [comment]
更新了一波hexo-douban@2.0.0 ，可以先尝试下。
